Repository TokTok/c-toxcore, pull requests merged in 2020-05, with the labels that each got.

#1467 Fix a bug in savedata loading when malloc fails.
  .restyled.yaml
  auto_tests/TCP_test.c
  auto_tests/conference_invite_merge_test.c
  auto_tests/conference_peer_nick_test.c
  auto_tests/conference_test.c
  auto_tests/encryptsave_test.c
  auto_tests/file_saving_test.c
  other/astyle/format-source
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxav/toxav.c
  toxcore/DHT.c
Labels: bug

#1473 Add a script to run Travis CI locally.
  .restyled.yaml
  .travis.yml
  .travis/cmake-linux
  other/analysis/check_recursion
  other/astyle/format-source
  other/docker/Dockerfile.ci
  other/docker/run-ci
Labels: overhead

#1489 typo: `NAC_LIBS` -> `NACL_LIBS`.
  toxcore/Makefile.inc
  toxencryptsave/Makefile.inc
Labels: typo

#1498 refactor: Limit scope of loop iterators.
  .github/settings.yml
  toxcore/TCP_connection.c
Labels: refactor

#1504 chore: Remove release-drafter configuration in favour of global one.
  .github/release-drafter.yml
Labels: chore

#1495 chore: Exclude imported libsodium sources from restyled.
  .restyled.yaml
Labels: chore

#1507 fix: Fix a bug preventing non-founders from rebooting a dead group from save
  toxcore/group_chats.c
Labels: bug

#1497 refactor: Use bash arrays instead of strings for static analysis scripts.
  other/analysis/gen-file.sh
  other/analysis/run-clang
  other/analysis/run-clang-analyze
  other/analysis/run-cppcheck
  other/analysis/run-gcc
  other/analysis/run-infer
  other/bootstrap_daemon/docker/update-sha256
Labels: refactor

#1513 refactor: Disallow multiple initialised declarators per decl.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/LAN_discovery.c
  toxcore/Messenger.c
  toxcore/TCP_connection.c
  toxcore/group.c
  toxcore/net_crypto.c
  toxcore/onion_client.c
  toxcore/tox.c
Labels: refactor

#1510 chore: Don't build pushes to branches, only to tags.
  .travis.yml
Labels: chore

#1514 refactor: Remove multi-declarators entirely.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/Messenger.c
  toxcore/group.c
  toxcore/net_crypto.c
  toxcore/network.c
  toxcore/onion_announce.c
  toxcore/onion_client.c
Labels: refactor

#1487 chore: Add autotools build to localbuild docker images.
  .hadolint.yaml
  other/docker/autotools/Dockerfile
  other/docker/cmake/Dockerfile
  other/docker/run-ci
  other/docker/travis/Dockerfile
Labels: chore

#1519 test: Add autotest for group moderation
  CMakeLists.txt
  auto_tests/group_announce_test.c
  auto_tests/group_message_test.c
  auto_tests/group_moderation_test.c
  auto_tests/groupchat_test.c
Labels: test

#1516 cleanup: Make pylint and mypy happy with bootstrap_node_info.py.
  other/fun/bootstrap_node_info.py
Labels: cleanup

#1530 style: Make group code compliant with the latest tokstyle.
  toxcore/Messenger.c
  toxcore/group_announce.c
  toxcore/group_chats.c
  toxcore/group_connection.c
  toxcore/group_moderation.c
Labels: style

#1515 style: Run restyled on Travis and Circle CI scripts.
  .circleci/cmake-asan
  .circleci/cmake-tsan
  .travis/autotools-linux
  .travis/cmake-freebsd-env.sh
  .travis/cmake-freebsd-stage1
  .travis/cmake-freebsd-stage2
  .travis/cmake-osx
  .travis/cmake-win32
  .travis/cmake-win64
  .travis/cmake-windows.sh
  .travis/flags-clang.sh
  .travis/flags-gcc.sh
  .travis/flags.sh
  .travis/tox-bootstrapd-docker
  .travis/upload-coverage
Labels: style

#1542 cleanup: Lots of groupchat code cleanup
  toxcore/group_announce.c
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/group_connection.c
  toxcore/group_connection.h
  toxcore/group_moderation.c
  toxcore/group_moderation.h
  toxcore/tox.c
Labels: cleanup

#1543 fix: Ngc req throttle
  toxcore/group_chats.c
  toxcore/group_connection.h
Labels: bug

#1544 fix: bug causing topic callback to sometimes give client the wrong peer id
  toxcore/group_chats.c
  toxcore/tox.api.h
  toxcore/tox.h
Labels: bug

#1545 refactor: A better way to get unique peer ID's
  toxcore/group_chats.c
  toxcore/group_chats.h
Labels: refactor

#1547 cleanup: More code cleanup
  toxcore/group_announce.c
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/group_connection.c
  toxcore/group_connection.h
  toxcore/group_moderation.c
  toxcore/group_moderation.h
Labels: cleanup

#1548 fix: Try to limit unnecessary sync request spam
  toxcore/group_chats.c
  toxcore/group_chats.h
Labels: bug

#1549 fix: Lower some group list limits to account for the new max packet size
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/group_connection.c
  toxcore/group_moderation.h
Labels: bug

#1550 fix: Add sanctions list entry purging
  toxcore/group_chats.c
  toxcore/group_moderation.c
  toxcore/tox.api.h
  toxcore/tox.h
Labels: bug

#1551 fix: Make save format moderator list a fixed size
  toxcore/group_chats.h
Labels: bug

#1553 refactor: peer deletion
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/group_connection.c
  toxcore/group_connection.h
  toxcore/tox.api.h
  toxcore/tox.c
  toxcore/tox.h
Labels: refactor

#1555 fix: handling sync errors and reconnections
  toxcore/group_chats.c
Labels: bug

#1560 fix: Put gcc_check_received_array() in main loop to remove possible recursion
  toxcore/group_chats.c
  toxcore/group_connection.c
Labels: bug

#1565 fix: a few more group handshake bugs
  toxcore/group_chats.c
Labels: bug

#1566 fix: Remove unnecessary 4 byte field from handshake packet
  toxcore/group_chats.c
  toxcore/group_connection.h
Labels: bug

#1567 fix: bug sometimes preventing handshakes from taking place
  toxcore/group_chats.c
  toxcore/group_connection.c
Labels: bug

#1568 fix: Make group TCP relay connections more robust
  toxcore/TCP_connection.c
  toxcore/TCP_connection.h
  toxcore/group_chats.c
  toxcore/group_chats.h
Labels: bug

#1569 fix: Make sure clients get peer exit event
  toxcore/group_chats.c
Labels: bug

#1570 fix: Make group announcements work without TCP requirement
  toxcore/Messenger.c
  toxcore/group_announce.c
  toxcore/group_chats.c
  toxcore/group_connection.h
Labels: bug

#1572 fix: bug causing invalid TCP nodes to be copied to group announcements
  toxcore/group_chats.c
  toxcore/group_connection.c
  toxcore/group_connection.h
Labels: bug

#1573 fix: bug preventing tcp relays from being saved
  toxcore/group_chats.c
Labels: bug

#1575 fix: Improve error handling when we add TCP relays
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/group_connection.c
  toxcore/group_connection.h
Labels: bug

#1577 fix: group exit type enum style: Foo_Bar -> FOO_BAR
  auto_tests/group_moderation_test.c
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/group_connection.c
Labels: bug

#1578 cleanup: More groupchat code cleanup
  toxcore/group_announce.c
  toxcore/group_announce.h
  toxcore/group_chats.c
  toxcore/group_connection.h
Labels: cleanup

#1579 refactor: invite sending and main do_gc loop
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/group_connection.h
  toxcore/tox.c
Labels: refactor

#1581 refactor: Improve self group announcement mechanism
  toxcore/Messenger.c
  toxcore/group_chats.c
  toxcore/group_chats.h
Labels: refactor

#1583 fix: bug preventing tcp connections from being initiated with initial peer
  toxcore/group_chats.c
Labels: bug

#1584 fix: Kill tcp connection when peer is marked for deletion
  toxcore/group_chats.c
  toxcore/group_connection.c
  toxcore/group_connection.h
Labels: bug

#1586 test: Fix tcp_relay_test by adding a second bootstrap node.
  auto_tests/tcp_relay_test.c
Labels: test

#1588 Fix: rejoin spam on handshake and remove unused function
  toxcore/group_chats.c
Labels: Fix

#1589 refactor: Add peer count back into ping packet
  toxcore/group_chats.c
  toxcore/group_chats.h
Labels: refactor

#1591 Refactor: Reduce unnecessary amount of group announcement spam
  toxcore/Messenger.c
  toxcore/group_chats.c
  toxcore/group_chats.h
Labels: refactor

#1592 Fix: Delete peers who send packets that we cannot decrypt
  toxcore/group_chats.c
Labels: Fix

#1593 Fix: A couple small fixes
  toxcore/group_chats.c
  toxcore/group_connection.c
  toxcore/group_connection.h
Labels: Fix

#1594 fix: Reset self announce timer even if we don't announce
  toxcore/group_chats.c
  toxcore/group_chats.h
Labels: bug

#1595 refactor: Simplify and improve group handshake protocol
  toxcore/group_chats.c
  toxcore/group_chats.h
Labels: refactor

#1597 fix: Broadcast a quit packet before we rejoin a group
  toxcore/group_chats.c
Labels: bug

#1600 cleanup: Some fixes and improvements to group autotests
  auto_tests/group_announce_test.c
  auto_tests/group_message_test.c
  auto_tests/group_moderation_test.c
  auto_tests/group_state_test.c
Labels: cleanup

#1601 refactor: Self-announce/self-connection refactor
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/Messenger.c
  toxcore/TCP_connection.c
  toxcore/TCP_connection.h
  toxcore/group_chats.c
  toxcore/group_chats.h
Labels: refactor

#1603 fix: bug causing invalid tcp relays to be copied to peer relay lists
  toxcore/group_chats.c
  toxcore/group_connection.c
  toxcore/group_connection.h
Labels: bug

#1604 refactor: Remove a bunch of useless group code from Messenger.c
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/group_chats.c
  toxcore/group_chats.h
Labels: refactor

#1605 fix: possible null dereference and fix some variable name issues
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/Messenger.c
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/tox.api.h
  toxcore/tox.c
  toxcore/tox.h
Labels: bug

#1606 feat: Add self_disconnected exit type
  toxcore/Messenger.c
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/tox.api.h
  toxcore/tox.h
Labels: enhancement

#1607 refactor: Improve TCP relay sending and storing
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/group_connection.c
  toxcore/group_connection.h
Labels: refactor

#1608 feat: Fix and complete group manual disconnect functionality
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/tox.api.h
  toxcore/tox.c
  toxcore/tox.h
Labels: enhancement

#1609 fix: Connected peers don't need to receive group announcements
  toxcore/group_chats.c
Labels: bug

#1610 fix: dereference of null pointer when we rejoin a group after being ki…
  toxcore/group_chats.c
Labels: bug

#1611 chore: some API fixes/modifications
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/tox.api.h
  toxcore/tox.c
  toxcore/tox.h
Labels: chore

#1612 cleanup: Remove useless function and improve reconnect API error handling
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/tox.api.h
  toxcore/tox.c
  toxcore/tox.h
Labels: cleanup

#1613 docs: Update groupchat docs
  docs/DHT-Group-Chats.md
Labels: documentation

#1616 chore: Add backwards compatibility code for onion
  auto_tests/onion_test.c
  toxcore/network.h
  toxcore/onion.c
  toxcore/onion_announce.c
  toxcore/onion_announce.h
  toxcore/onion_client.c
Labels: chore

#1619 cleanup: Remove unused packet IDs
  auto_tests/onion_test.c
  toxcore/network.h
  toxcore/onion.c
Labels: cleanup

#1620 fix: Improve group TCP connections
  toxcore/group_chats.c
  toxcore/group_connection.h
Labels: bug

#1557 chore: Add conan support
  CMakeLists.txt
  appveyor.yml
  cmake/Dependencies.cmake
  cmake/ModulePackage.cmake
  conanfile.py
Labels: chore
