Repository TokTok/c-toxcore, pull requests merged in 2020-11, with the labels that each got.

#1667 chore: Update tox-bootstrapd checksum due to newer packages in Alpine
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
Labels: chore

#1664 cleanup: use heap memory instead of stack for large variables
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxav/audio.c
  toxcore/DHT.c
Labels: cleanup

#1663 fix: Fix file tests on windows
  auto_tests/file_saving_test.c
  auto_tests/save_compatibility_test.c
Labels: bug
