Repository TokTok/c-toxcore, pull requests merged in 2021-12, with the labels that each got.

#1713 test: Add some unit tests for important internal DHT functions.
  .cirrus.yml
  CMakeLists.txt
  toxcore/BUILD.bazel
  toxcore/DHT.h
  toxcore/DHT_test.cc
Labels: test

#1602 fix: Fix buffer over-read when a peer leaves a conference
  toxcore/group.c
Labels: bug

#1716 chore: Use toktok-stack docker image with built third_party.
  .cirrus.yml
  toxav/toxav.c
  toxcore/DHT.h
  toxcore/TCP_connection.h
  toxcore/friend_connection.h
  toxcore/network.c
Labels: chore

#1723 chore: Run infer static analyser on circle ci builds.
  .circleci/config.yml
  .github/settings.yml
  .travis/cmake-linux
  other/analysis/gen-file.sh
  other/analysis/run-check-recursion
  other/analysis/run-clang
  other/analysis/run-infer
  testing/DHT_test.c
  toxcore/Messenger.c
  toxcore/ccompat.h
  toxcore/crypto_core.c
  toxencryptsave/BUILD.bazel
  toxencryptsave/toxencryptsave.api.h
  toxencryptsave/toxencryptsave.c
  toxencryptsave/toxencryptsave.h
Labels: chore

#1725 cleanup: add some missing null checks
  toxav/bwcontroller.c
  toxav/ring_buffer.c
  toxav/rtp.c
  toxav/toxav.c
  toxcore/group.c
Labels: cleanup

#1729 cleanup: Ensure that error codes are always initialised.
  other/analysis/run-gcc
  toxcore/tox.c
Labels: cleanup

#1732 cleanup: Refactor kill_nonused_tcp()
  toxcore/TCP_connection.c
Labels: cleanup

#1733 cleanup: Minor fixes in test code.
  auto_tests/save_compatibility_test.c
  testing/afl_toxsave.c
Labels: cleanup

#1727 cleanup: Avoid endian-specific code in `crypto_core`.
  toxcore/crypto_core.api.h
  toxcore/crypto_core.c
  toxcore/crypto_core.h
  toxcore/crypto_core_test.cc
Labels: cleanup

#1734 chore: Add logger to onion and onion announce objects
  auto_tests/onion_test.c
  other/DHT_bootstrap.c
  other/bootstrap_daemon/src/config.c
  other/bootstrap_daemon/src/tox-bootstrapd.c
  toxcore/Messenger.c
  toxcore/onion.c
  toxcore/onion.h
  toxcore/onion_announce.c
  toxcore/onion_announce.h
Labels: chore

#1735 cleanup: Use `static_assert` instead of preprocessor `#error`.
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/network.c
  toxcore/onion_announce.c
  toxcore/onion_announce.h
  toxcore/tox.c
Labels: cleanup

#1736 chore: Add workflow for running coverity scan.
  .github/workflows/coverity-scan.yml
Labels: chore

#1743 chore: Minor cleanups of warnings given by cppcheck.
  auto_tests/TCP_test.c
  auto_tests/crypto_test.c
  auto_tests/network_test.c
  auto_tests/save_load_test.c
  auto_tests/set_name_test.c
  auto_tests/set_status_message_test.c
  auto_tests/toxav_basic_test.c
  auto_tests/toxav_many_test.c
  toxcore/Messenger.c
  toxcore/ccompat.h
Labels: chore

#1744 cleanup: Enforce for loop consistency.
  toxav/audio.c
  toxav/groupav.c
  toxav/msi.c
  toxav/ring_buffer.c
  toxav/toxav.c
  toxcore/crypto_core.c
  toxcore/group.c
Labels: cleanup

#1746 chore: Add clang-tidy review github workflow.
  .github/workflows/clang-tidy-review.yml
Labels: chore

#1738 chore: Add missing `sudo` to coverity apt-get calls.
  .github/workflows/coverity-scan.yml
Labels: chore

#1737 refactor: Fix previous refactor
  other/bootstrap_daemon/src/config.c
Labels: refactor

#1742 test: Add a simple test for `ip_ntoa`.
  .circleci/config.yml
  .github/settings.yml
  .github/workflows/clang-tidy-review.yml
  build/Makefile.am
  other/analysis/run-clang-tidy
  other/bootstrap_daemon/src/tox-bootstrapd.c
  toxcore/BUILD.bazel
  toxcore/ccompat.h
  toxcore/network.c
  toxcore/network_test.cc
Labels: test

#1740 cleanup: Put fatal errors where API return values should be impossible
  toxcore/tox.c
Labels: cleanup

#1747 cleanup: Fix some clang-tidy warnings and make them errors.
  other/analysis/run-clang-tidy
  other/bootstrap_daemon/src/log.c
  other/bootstrap_daemon/src/tox-bootstrapd.c
  toxav/msi.c
  toxcore/DHT.c
  toxcore/tox.c
  toxcore/tox_api.c
  toxencryptsave/toxencryptsave.c
Labels: cleanup

#1751 fix: Fixed uninitialised value copy.
  toxcore/TCP_client.c
  toxcore/TCP_client.h
Labels: bug

#1752 chore: Use an incrementing version number for coverity scans.
  .github/workflows/coverity-scan.yml
Labels: chore

#1333 refactor: Clean up friend loading.
  toxcore/Messenger.c
Labels: refactor

#1754 fix: off-by-one error caused by integer division without proper cast
  toxcore/net_crypto.c
Labels: bug

#1753 cleanup: use crypto_memzero to wipe secret keys when no longer in use
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/TCP_connection.c
  toxcore/TCP_server.c
  toxcore/onion.c
  toxcore/ping.c
Labels: cleanup

#1307 refactor: Split toxav_iterate into audio and video part
  toxav/toxav.api.h
  toxav/toxav.c
  toxav/toxav.h
Labels: refactor

#1759 cleanup: address some unused return values
  toxcore/TCP_client.c
  toxcore/network.c
  toxcore/network.h
  toxcore/ping.c
  toxcore/ping.h
Labels: cleanup

#1761 cleanup: Don't include `"config.h"` unless needed.
  toxav/audio.c
  toxav/bwcontroller.c
  toxav/groupav.c
  toxav/msi.c
  toxav/rtp.c
  toxav/toxav.c
  toxav/video.c
  toxcore/DHT.c
  toxcore/LAN_discovery.c
  toxcore/Messenger.c
  toxcore/TCP_client.c
  toxcore/TCP_connection.c
  toxcore/TCP_server.c
  toxcore/crypto_core.c
  toxcore/friend_connection.c
  toxcore/friend_requests.c
  toxcore/group.c
  toxcore/list.c
  toxcore/logger.c
  toxcore/net_crypto.c
  toxcore/network.c
  toxcore/onion.c
  toxcore/onion_announce.c
  toxcore/onion_client.c
  toxcore/ping.c
  toxcore/ping_array.c
  toxcore/tox.c
  toxcore/util.c
Labels: cleanup

#1762 chore: Add autotools build; exempt crypto_pwhash from tokstyle.
  .github/workflows/ci.yml
  .travis/autotools-linux
  auto_tests/Makefile.inc
  testing/BUILD.bazel
  toxav/BUILD.bazel
  toxcore/BUILD.bazel
  toxcore/crypto_core.c
  toxcore/crypto_core_mem.c
  toxcore/network.c
  toxencryptsave/BUILD.bazel
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/crypto_pwhash_scryptsalsa208sha256.h
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/crypto_scrypt.h
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/export.h
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/pbkdf2-sha256.h
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/runtime.h
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/sysendian.h
  toxencryptsave/toxencryptsave.c
Labels: chore

#1770 cleanup: merge onion.c changes from new groupchats fork
  toxcore/onion.c
Labels: cleanup

#1768 chore: merge DHT changes from new groupchats fork
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/network.c
  toxcore/network.h
Labels: chore

#1772 chore: Add .cc files to the static analysis.
  other/analysis/gen-file.sh
Labels: chore

#1773 chore: Fix gen-file.sh: it wasn't globbing properly.
  .circleci/config.yml
  other/analysis/gen-file.sh
  other/analysis/run-clang
  toxcore/crypto_core_test.cc
Labels: chore

#1774 chore: Remove config.h.
  auto_tests/TCP_test.c
  auto_tests/bootstrap_test.c
  auto_tests/conference_av_test.c
  auto_tests/conference_double_invite_test.c
  auto_tests/conference_invite_merge_test.c
  auto_tests/conference_peer_nick_test.c
  auto_tests/conference_simple_test.c
  auto_tests/conference_test.c
  auto_tests/conference_two_test.c
  auto_tests/crypto_test.c
  auto_tests/dht_test.c
  auto_tests/encryptsave_test.c
  auto_tests/file_saving_test.c
  auto_tests/file_transfer_test.c
  auto_tests/friend_connection_test.c
  auto_tests/friend_request_test.c
  auto_tests/invalid_tcp_proxy_test.c
  auto_tests/invalid_udp_proxy_test.c
  auto_tests/lan_discovery_test.c
  auto_tests/lossless_packet_test.c
  auto_tests/lossy_packet_test.c
  auto_tests/messenger_test.c
  auto_tests/network_test.c
  auto_tests/onion_test.c
  auto_tests/overflow_recvq_test.c
  auto_tests/overflow_sendq_test.c
  auto_tests/reconnect_test.c
  auto_tests/save_friend_test.c
  auto_tests/save_load_test.c
  auto_tests/send_message_test.c
  auto_tests/set_name_test.c
  auto_tests/set_status_message_test.c
  auto_tests/skeleton_test.c
  auto_tests/tcp_relay_test.c
  auto_tests/tox_many_tcp_test.c
  auto_tests/tox_many_test.c
  auto_tests/tox_one_test.c
  auto_tests/tox_strncasecmp_test.c
  auto_tests/toxav_basic_test.c
  auto_tests/toxav_many_test.c
  auto_tests/typing_test.c
  auto_tests/version_test.c
  configure.ac
  testing/misc_tools.c
  toxcore/crypto_core.c
  toxcore/crypto_core_mem.c
  toxcore/network.c
  toxencryptsave/toxencryptsave.c
Labels: chore

#1777 cleanup: Remove crypto_pwhash import.
  .restyled.yaml
  auto_tests/Makefile.inc
  toxcore/ccompat.h
  toxcore/crypto_core_mem.c
  toxcore/logger.c
  toxcore/tox_api.c
  toxencryptsave/BUILD.bazel
  toxencryptsave/Makefile.inc
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/crypto_pwhash_scryptsalsa208sha256.h
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/crypto_scrypt-common.c
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/crypto_scrypt.h
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/export.h
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/nosse/pwhash_scryptsalsa208sha256_nosse.c
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/note_to_maintainers.txt
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/pbkdf2-sha256.c
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/pbkdf2-sha256.h
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/pwhash_scryptsalsa208sha256.c
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/runtime.c
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/runtime.h
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/scrypt_platform.c
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/sse/pwhash_scryptsalsa208sha256_sse.c
  toxencryptsave/crypto_pwhash_scryptsalsa208sha256/sysendian.h
  toxencryptsave/defines.h
  toxencryptsave/toxencryptsave.c
Labels: cleanup

#1776 cleanup: remove unused function argument from set_tcp_connection_status()
  toxcore/TCP_connection.c
Labels: cleanup

#1775 cleanup: Remove apidsl for everything except the public API.
  CMakeLists.txt
  auto_tests/BUILD.bazel
  toxcore/DHT.h
  toxcore/LAN_discovery.api.h
  toxcore/LAN_discovery.h
  toxcore/crypto_core.api.h
  toxcore/crypto_core.h
  toxcore/mono_time.h
  toxcore/network.h
  toxcore/ping.api.h
  toxcore/ping.h
  toxcore/ping_array.api.h
  toxcore/ping_array.h
Labels: cleanup

#1778 chore: Tie down the use of doxygen comments.
  toxav/audio.c
  toxav/rtp.c
  toxav/toxav.c
  toxav/toxav_old.c
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/mono_time.h
  toxcore/net_crypto.c
  toxcore/net_crypto.h
  toxcore/state.h
Labels: chore

#1779 chore: Update toktok-stack version.
  .cirrus.yml
Labels: chore

#1783 cleanup: fix format-source
  other/astyle/format-source
Labels: cleanup

#1786 cleanup: Remove apidsl; remove `crypto_memcmp`.
  .cirrus.yml
  CMakeLists.txt
  cmake/ApiDsl.cmake
  other/astyle/format-source
  toxav/BUILD.bazel
  toxav/toxav.api.h
  toxav/toxav.h
  toxcore/BUILD.bazel
  toxcore/ccompat.h
  toxcore/crypto_core.c
  toxcore/crypto_core.h
  toxcore/crypto_core_mem.c
  toxcore/crypto_core_test.cc
  toxcore/group.c
  toxcore/mono_time.c
  toxcore/net_crypto.c
  toxcore/network.c
  toxcore/onion_announce.c
  toxcore/tox.api.h
  toxcore/tox.c
  toxcore/tox.h
  toxencryptsave/toxencryptsave.api.h
  toxencryptsave/toxencryptsave.h
Labels: cleanup

#1789 refactor: rename variable to clarify purpose
  toxcore/DHT.c
Labels: refactor

#1790 cleanup: remove redundant (and incorrect) comments
  toxcore/crypto_core_mem.c
Labels: cleanup

#1792 chore: Add cross compilation CI targets.
  .github/workflows/ci.yml
  .travis/cmake-windows.sh
Labels: chore

#1794 chore: Move cmake-freebsd-stage2 back into the toxcore repo.
  .github/workflows/ci.yml
  .travis/cmake-freebsd-stage2
Labels: chore

#1797 cleanup: Move `sodium.h` include to front of network.c.
  toxcore/network.c
Labels: cleanup

#1801 chore: Fix up a few source code comment and style issues.
  .cirrus.yml
  toxav/bwcontroller.h
  toxav/groupav.h
  toxav/msi.c
  toxav/rtp.c
  toxav/rtp.h
  toxcore/logger.c
  toxcore/tox.h
  toxencryptsave/toxencryptsave.c
  toxencryptsave/toxencryptsave.h
Labels: chore

#1798 chore: merge friend_connections from NGC fork
  toxcore/BUILD.bazel
  toxcore/friend_connection.c
  toxcore/friend_connection.cc
  toxcore/friend_connection.h
Labels: chore

#1807 chore: Don't run CI on master branch pushes.
  .github/workflows/ci.yml
Labels: chore

#1810 chore: Remove apidsl comment from tox.h.
  .cirrus.yml
  toxcore/tox.h
Labels: chore

#1812 chore: Only push versioned docker image on tag builds.
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  .travis/tox-bootstrapd-docker
Labels: chore

#1813 chore: Login to dockerhub before trying to push to dockerhub.
  .github/settings.yml
  .github/workflows/docker.yml
Labels: chore

#1816 cleanup: put breaks inside case braces
  toxav/msi.c
  toxav/toxav.c
  toxcore/group.c
Labels: cleanup

#1820 chore: Add macOS build.
  .github/settings.yml
  .github/workflows/ci.yml
  .travis/cmake-osx
Labels: chore

#1819 refactor: Extract some functions from the big run_auto_test function.
  auto_tests/run_auto_test.h
Labels: refactor

#1673 cleanup: Remove hardening code from DHT
  auto_tests/dht_test.c
  testing/DHT_test.c
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/onion_announce.c
Labels: cleanup

#1830 chore: Add "tcc" and "compcert" compiler targets.
  .cirrus.yml
  .github/settings.yml
  .github/workflows/ci.yml
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/ccompat.h
Labels: chore
