Repository TokTok/c-toxcore, pull requests merged in 2021-11, with the labels that each got.

#1703 chore: Upgrade to toktok-stack:0.0.11.
  .cirrus.yml
  .github/settings.yml
Labels: chore

#1705 fix: issue with save_load autotest
  auto_tests/save_load_test.c
Labels: bug, test

#1706 chore: Enable cimple tests on cirrus build.
  .cirrus.yml
  .github/settings.yml
Labels: chore

#1698 fix: bug causing API to report wrong self connection status
  toxcore/onion_client.c
Labels: bug

#1699 fix: some friend connection issues
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/net_crypto.c
Labels: bug

#1708 perf: reduce calling into Mono_Time in DHT
  toxcore/DHT.c
Labels: performance

#1672 docs: Add instructions for building unit tests to INSTALL.md
  INSTALL.md
Labels: documentation
