Repository TokTok/c-toxcore, pull requests merged in 2022-02, with the labels that each got.

#1945 fix: Fix bootstrap on emscripten/wasm.
  auto_tests/TCP_test.c
  other/bootstrap_daemon/docker/Dockerfile
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/docker/update-sha256
  toxcore/TCP_client.c
  toxcore/TCP_client.h
  toxcore/TCP_common.c
  toxcore/TCP_common.h
  toxcore/TCP_connection.c
  toxcore/TCP_connection.h
  toxcore/TCP_server.c
  toxcore/net_crypto.c
  toxcore/network.c
  toxcore/network.h
  toxcore/tox.c
Labels: bug

#1950 feat: Add WASM build for toxcore and websocket bootstrap node.
  .github/settings.yml
  .github/workflows/docker.yml
  .hadolint.yaml
  heroku.yml
  other/bootstrap_daemon/docker/update-sha256
  other/bootstrap_daemon/websocket/Dockerfile
  other/bootstrap_daemon/websocket/entrypoint.sh
  other/bootstrap_daemon/websocket/keys
  other/bootstrap_daemon/websocket/websockify/go.mod
  other/bootstrap_daemon/websocket/websockify/websockify.go
  other/emscripten/Dockerfile
Labels: enhancement

#1956 chore: Disable some cimple warnings for now.
  testing/BUILD.bazel
Labels: chore

#1955 cleanup: Properly copy Node_format using serialized format
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
Labels: chore, cleanup

#1958 chore: Make run-infer script use docker.
  other/analysis/run-infer
  toxcore/group.c
Labels: chore

#1964 cleanup: Don't pass the whole DHT object to lan discovery.
  other/DHT_bootstrap.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/src/tox-bootstrapd.c
  toxcore/LAN_discovery.c
  toxcore/LAN_discovery.h
  toxcore/friend_connection.c
Labels: cleanup

#1948 fix: potential freeing of an immutable static buffer
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/network.c
Labels: bug

#1968 cleanup: Ensure we limit the system headers included in .h files.
  .circleci/config.yml
  .github/workflows/ci.yml
  .gitignore
  other/analysis/check_includes
  other/analysis/check_recursion
  toxav/audio.c
  toxav/msi.h
  toxcore/ccompat.h
  toxcore/onion_client.c
Labels: cleanup

#1972 chore: Make the last few remaining top level comments doxygen style.
  toxav/groupav.c
  toxav/groupav.h
  toxav/msi.c
  toxav/ring_buffer.c
  toxav/ring_buffer.h
  toxav/rtp.c
  toxav/toxav.h
  toxav/toxav_old.c
  toxencryptsave/toxencryptsave.c
  toxencryptsave/toxencryptsave.h
Labels: chore

#1974 docs: Add doxygen configuration and netlify publishing.
  .doxygen.conf
  netlify.toml
  other/docker/doxygen/Dockerfile
  other/docker/doxygen/run
  testing/BUILD.bazel
  toxav/rtp.h
  toxav/toxav.h
  toxcore/tox.h
Labels: documentation

#1975 refactor: use proper method for generating random numbers in a range
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/crypto_core.c
  toxcore/crypto_core.h
  toxcore/onion_client.c
Labels: refactor

#1976 docs: Make crypto_core.h appear on doxygen.
  .github/scripts/cmake-linux
  .github/scripts/cmake-osx
  .github/settings.yml
  docs/Doxyfile
  netlify.toml
  other/docker/doxygen/Dockerfile
  toxav/toxav.h
  toxcore/crypto_core.c
  toxcore/crypto_core.h
  toxcore/ping_array.h
  toxcore/tox.h
Labels: documentation

#1978 chore: Release 0.2.14
  CHANGELOG.md
  CMakeLists.txt
  configure.ac
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  so.version
  toxcore/tox.h
Labels: chore

#1980 fix: Reduce logging verbosity in TCP server.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/TCP_server.c
Labels: bug

#1984 fix: Reduce logging verbosity even more.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/TCP_common.c
  toxcore/TCP_server.c
Labels: bug

#1983 chore: Release 0.2.15
  CHANGELOG.md
  CMakeLists.txt
  configure.ac
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  so.version
  toxcore/tox.h
Labels: chore

#1979 chore: Update readme header
  README.md
Labels: chore

#1985 cleanup: Split msi callback array into 1 member per callback
  toxav/msi.c
  toxav/msi.h
Labels: cleanup

#1982 chore: Add an easy way to run autotools and circleci builds locally.
  .github/scripts/flags-clang.sh
  other/docker/autotools/run
  other/docker/circleci/Dockerfile
  other/docker/circleci/run
  other/docker/doxygen/run
Labels: chore

#1987 cleanup: Comply with new cimple callback rules.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/network.c
  toxcore/tox.c
Labels: cleanup

#1952 feat: Add async event handling (callbacks) code.
  .circleci/config.yml
  .github/workflows/ci.yml
  CMakeLists.txt
  auto_tests/BUILD.bazel
  auto_tests/tox_dispatch_test.c
  auto_tests/tox_events_test.c
  other/analysis/gen-file.sh
  other/make_single_file
  toxcore/BUILD.bazel
  toxcore/Makefile.inc
  toxcore/ccompat.c
  toxcore/ccompat.h
  toxcore/events/conference_connected.c
  toxcore/events/conference_invite.c
  toxcore/events/conference_message.c
  toxcore/events/conference_peer_list_changed.c
  toxcore/events/conference_peer_name.c
  toxcore/events/conference_title.c
  toxcore/events/events_alloc.c
  toxcore/events/events_alloc.h
  toxcore/events/file_chunk_request.c
  toxcore/events/file_recv.c
  toxcore/events/file_recv_chunk.c
  toxcore/events/file_recv_control.c
  toxcore/events/friend_connection_status.c
  toxcore/events/friend_lossless_packet.c
  toxcore/events/friend_lossy_packet.c
  toxcore/events/friend_message.c
  toxcore/events/friend_name.c
  toxcore/events/friend_read_receipt.c
  toxcore/events/friend_request.c
  toxcore/events/friend_status.c
  toxcore/events/friend_status_message.c
  toxcore/events/friend_typing.c
  toxcore/events/self_connection_status.c
  toxcore/net_crypto.c
  toxcore/net_crypto.h
  toxcore/tox.h
  toxcore/tox_dispatch.c
  toxcore/tox_dispatch.h
  toxcore/tox_events.c
  toxcore/tox_events.h
Labels: enhancement

#1988 cleanup: Make LAN discovery thread-safe without data races.
  other/DHT_bootstrap.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/src/tox-bootstrapd.c
  toxcore/LAN_discovery.c
  toxcore/LAN_discovery.h
  toxcore/friend_connection.c
Labels: cleanup

#1993 feat: Add binary packing functions for tox events.
  .circleci/config.yml
  .github/scripts/cmake-linux
  .github/scripts/cmake-osx
  .github/scripts/cmake-win32
  .github/scripts/cmake-win64
  .github/scripts/cmake-windows.sh
  .github/scripts/sonar-prepare
  .github/settings.yml
  .github/workflows/ci.yml
  .hadolint.yaml
  CMakeLists.txt
  appveyor.yml
  auto_tests/Makefile.inc
  auto_tests/tox_dispatch_test.c
  cmake/Dependencies.cmake
  conanfile.py
  configure.ac
  other/analysis/check_includes
  other/analysis/gen-file.sh
  other/bootstrap_daemon/docker/Dockerfile
  other/docker/autotools/Dockerfile
  other/docker/circleci/Dockerfile
  other/docker/tcc/Dockerfile
  other/docker/tcc/run
  other/docker/windows/Dockerfile
  other/docker/windows/build_dependencies.sh
  other/docker/windows/get_packages.sh
  other/emscripten/Dockerfile
  other/emscripten/build
  toxcore/BUILD.bazel
  toxcore/events/conference_connected.c
  toxcore/events/conference_invite.c
  toxcore/events/conference_message.c
  toxcore/events/conference_peer_list_changed.c
  toxcore/events/conference_peer_name.c
  toxcore/events/conference_title.c
  toxcore/events/events_alloc.h
  toxcore/events/file_chunk_request.c
  toxcore/events/file_recv.c
  toxcore/events/file_recv_chunk.c
  toxcore/events/file_recv_control.c
  toxcore/events/friend_connection_status.c
  toxcore/events/friend_lossless_packet.c
  toxcore/events/friend_lossy_packet.c
  toxcore/events/friend_message.c
  toxcore/events/friend_name.c
  toxcore/events/friend_read_receipt.c
  toxcore/events/friend_request.c
  toxcore/events/friend_status.c
  toxcore/events/friend_status_message.c
  toxcore/events/friend_typing.c
  toxcore/events/self_connection_status.c
  toxcore/tox_events.c
  toxcore/tox_events.h
Labels: enhancement

#1996 feat: Add unpacker functions for events structures.
  CMakeLists.txt
  auto_tests/tox_dispatch_test.c
  toxcore/BUILD.bazel
  toxcore/Makefile.inc
  toxcore/events/conference_connected.c
  toxcore/events/conference_invite.c
  toxcore/events/conference_message.c
  toxcore/events/conference_peer_list_changed.c
  toxcore/events/conference_peer_name.c
  toxcore/events/conference_title.c
  toxcore/events/events_alloc.h
  toxcore/events/file_chunk_request.c
  toxcore/events/file_recv.c
  toxcore/events/file_recv_chunk.c
  toxcore/events/file_recv_control.c
  toxcore/events/friend_connection_status.c
  toxcore/events/friend_lossless_packet.c
  toxcore/events/friend_lossy_packet.c
  toxcore/events/friend_message.c
  toxcore/events/friend_name.c
  toxcore/events/friend_read_receipt.c
  toxcore/events/friend_request.c
  toxcore/events/friend_status.c
  toxcore/events/friend_status_message.c
  toxcore/events/friend_typing.c
  toxcore/events/self_connection_status.c
  toxcore/tox_events.c
  toxcore/tox_events.h
  toxcore/tox_unpack.c
  toxcore/tox_unpack.h
Labels: enhancement

#1999 chore: Speed up cmake builds with `UNITY_BUILD`.
  .circleci/cmake-asan
  .circleci/cmake-tsan
  CMakeLists.txt
Labels: chore

#2002 cleanup: Add nonnull annotations to function definitions.
  .github/scripts/flags-clang.sh
  .github/scripts/flags-gcc.sh
  netlify.toml
  other/analysis/run-clang
  other/analysis/run-clang-tidy
  other/analysis/run-gcc
  other/bootstrap_daemon/docker/Dockerfile
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/ccompat.h
  toxcore/crypto_core.c
  toxcore/tox.c
Labels: cleanup

#2010 chore: Remove duplicate source file in autotools build.
  toxcore/Makefile.inc
Labels: chore

#2007 feat: add bash-completion for tox-bootstrapd
  CMakeLists.txt
  other/bootstrap_daemon/bash-completion/completions/tox-bootstrapd
  other/bootstrap_daemon/docker/Dockerfile
  other/bootstrap_daemon/src/Makefile.inc
Labels: enhancement

#2018 fix: Coverty scan
  .github/workflows/coverity-scan.yml
Labels: bug, chore

#2019 chore: Silence clang compile warnings causing circle-ci/asan to fail
  .github/scripts/flags-clang.sh
Labels: chore

#2022 cleanup: Split tox_unpack into two smaller libs
  CMakeLists.txt
  toxcore/BUILD.bazel
  toxcore/Makefile.inc
  toxcore/bin_unpack.c
  toxcore/bin_unpack.h
  toxcore/events/conference_connected.c
  toxcore/events/conference_invite.c
  toxcore/events/conference_message.c
  toxcore/events/conference_peer_list_changed.c
  toxcore/events/conference_peer_name.c
  toxcore/events/conference_title.c
  toxcore/events/file_chunk_request.c
  toxcore/events/file_recv.c
  toxcore/events/file_recv_chunk.c
  toxcore/events/file_recv_control.c
  toxcore/events/friend_connection_status.c
  toxcore/events/friend_lossless_packet.c
  toxcore/events/friend_lossy_packet.c
  toxcore/events/friend_message.c
  toxcore/events/friend_name.c
  toxcore/events/friend_read_receipt.c
  toxcore/events/friend_request.c
  toxcore/events/friend_status.c
  toxcore/events/friend_status_message.c
  toxcore/events/friend_typing.c
  toxcore/events/self_connection_status.c
  toxcore/tox_unpack.c
  toxcore/tox_unpack.h
Labels: cleanup

#2021 chore: Disable non-null attributes by default.
  .circleci/cmake-ubsan
  toxcore/attributes.h
Labels: chore

#1992 chore: Set up an Android CI job
  .github/scripts/cmake-android
  .github/workflows/ci.yml
Labels: chore

#2016 docs: Add libmsgpack dependency in INSTALL.md
  INSTALL.md
Labels: documentation

#2013 cleanup: Don't use VLAs for huge allocations.
  auto_tests/encryptsave_test.c
  auto_tests/save_friend_test.c
  auto_tests/tox_one_test.c
  other/analysis/check_includes
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/ccompat.h
  toxcore/onion_announce.c
  toxcore/onion_client.c
Labels: cleanup

#2024 perf: Reduce minimal encoding size of packed events.
  auto_tests/BUILD.bazel
  auto_tests/tox_dispatch_test.c
  auto_tests/tox_events_test.c
  other/BUILD.bazel
  other/bootstrap_daemon/BUILD.bazel
  other/fun/BUILD.bazel
  testing/BUILD.bazel
  toxcore/BUILD.bazel
  toxcore/events/conference_connected.c
  toxcore/events/conference_invite.c
  toxcore/events/conference_message.c
  toxcore/events/conference_peer_list_changed.c
  toxcore/events/conference_peer_name.c
  toxcore/events/conference_title.c
  toxcore/events/file_chunk_request.c
  toxcore/events/file_recv.c
  toxcore/events/file_recv_chunk.c
  toxcore/events/file_recv_control.c
  toxcore/events/friend_connection_status.c
  toxcore/events/friend_lossless_packet.c
  toxcore/events/friend_lossy_packet.c
  toxcore/events/friend_message.c
  toxcore/events/friend_name.c
  toxcore/events/friend_read_receipt.c
  toxcore/events/friend_request.c
  toxcore/events/friend_status.c
  toxcore/events/friend_status_message.c
  toxcore/events/friend_typing.c
  toxcore/events/self_connection_status.c
  toxcore/tox_events.c
  toxcore/tox_events.h
Labels: performance

#2025 chore: add continous fuzzing to our CI
  .github/workflows/cflite_batch.yml
  .github/workflows/cflite_cron.yml
Labels: chore

#2026 chore: Fix implicit declaration warning in fuzz build
  toxcore/crypto_core.c
Labels: chore

#2028 fix: syntax error introduced in 8bf37994fd12acec9e3010437502f478399b99b4
  .github/workflows/cflite_batch.yml
  .github/workflows/cflite_cron.yml
Labels: bug

#2030 chore: expand fuzzing to toxsave
  .clusterfuzzlite/build.sh
Labels: chore

#2031 fix: remove bogus asserts in fuzzer harness
  testing/fuzzing/toxsave_harness.cc
Labels: bug

#2035 chore: fine tune fuzzing settings
  .github/workflows/cflite_batch.yml
  .github/workflows/cflite_cron.yml
Labels: chore

#2033 cleanup: Add some more error path logging to TCP server code.
  .github/settings.yml
  .github/workflows/ci.yml
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/TCP_server.c
Labels: cleanup

#1668 perf: Take advantage of fast networks for file transfers
  auto_tests/set_name_test.c
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/tox.c
Labels: performance

#2041 fix: file transfer bug introduced in commit 2073d02
  toxcore/Messenger.c
Labels: bug

#2039 refactor: Add a bit more logging; change WARNING to ERROR.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/Messenger.c
  toxcore/TCP_common.c
  toxcore/TCP_server.c
  toxcore/net_crypto.c
  toxcore/network.c
Labels: refactor

#2047 feat: Improve how we share TCP relays with friends
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/TCP_connection.c
  toxcore/TCP_connection.h
  toxcore/friend_connection.c
  toxcore/friend_connection.h
  toxcore/net_crypto.c
  toxcore/net_crypto.h
Labels: enhancement

#2052 fix: Fix return type of functions returning uint64_t.
  toxcore/events/file_recv.c
  toxcore/events/file_recv_chunk.c
  toxcore/tox_events.h
Labels: bug

#2056 cleanup: Avoid implicit boolean and floating point conversions in decls.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/TCP_server.c
  toxcore/net_crypto.c
  toxcore/network.c
  toxcore/onion_announce.c
  toxcore/onion_client.c
  toxcore/tox.c
Labels: cleanup

#2055 cleanup: Avoid implicit bool conversions in logical operators.
  toxav/audio.c
  toxav/bwcontroller.c
  toxav/groupav.c
  toxav/msi.c
  toxav/ring_buffer.c
  toxav/rtp.c
  toxav/toxav.c
  toxav/video.c
  toxcore/DHT.c
  toxcore/Messenger.c
  toxcore/TCP_common.c
  toxcore/TCP_connection.c
  toxcore/TCP_server.c
  toxcore/friend_connection.c
  toxcore/group.c
  toxcore/list.c
  toxcore/logger.c
  toxcore/net_crypto.c
  toxcore/network.c
  toxcore/onion_client.c
  toxcore/tox.c
  toxencryptsave/toxencryptsave.c
Labels: cleanup

#2053 cleanup: Enable tokstyle's `-Wlarge-struct-params`.
  auto_tests/onion_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  testing/BUILD.bazel
  toxcore/onion_announce.c
  toxcore/onion_announce.h
Labels: cleanup

#2058 fix: properly deallocate frozen peers
  toxcore/group.c
Labels: bug

#2066 test: Add a profiling script and Dockerfile.
  other/docker/perf/Dockerfile
  other/docker/perf/entrypoint.sh
  other/docker/perf/run
Labels: test

#2073 chore: Fix build-args in win32/win64 docker build.
  .github/workflows/docker.yml
Labels: chore

#2074 chore: Make coverity scan a nightly job.
  .github/workflows/coverity-scan.yml
Labels: chore

#2079 cleanup: Remove unused execution trace library.
  CMakeLists.txt
  other/analysis/gen-file.sh
  testing/BUILD.bazel
  testing/trace.cc
Labels: cleanup

#2064 fix: toxsave memory leak while loading groups
  toxcore/group.c
Labels: bug

#2084 fix: out-of-memory condition by corrupted save file
  toxcore/group.c
Labels: bug

#2075 chore: Add a .clang-format that mostly agrees with astyle.
  .clang-format
  .restyled.yaml
  testing/fuzzing/bootstrap_harness.cc
  testing/fuzzing/toxsave_harness.cc
  testing/random_testing.cc
  toxav/ring_buffer_test.cc
  toxav/rtp_test.cc
  toxcore/DHT_test.cc
  toxcore/Messenger.c
  toxcore/ccompat.h
  toxcore/crypto_core_test.cc
  toxcore/friend_connection_test.cc
  toxcore/list_test.cc
  toxcore/logger.h
  toxcore/mono_time_test.cc
  toxcore/network_test.cc
  toxcore/ping_array_test.cc
  toxcore/util_test.cc
Labels: chore

#2086 cleanup: Enable most cppcheck warnings as errors.
  auto_tests/auto_test_support.c
  auto_tests/auto_test_support.h
  other/analysis/gen-file.sh
  other/analysis/run-cppcheck
  other/analysis/run-gcc
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/fun/create_common.h
  toxav/toxav.c
  toxcore/LAN_discovery.h
  toxcore/Messenger.c
  toxcore/bin_unpack.h
  toxcore/crypto_core.c
  toxcore/events/friend_status.c
  toxcore/events/friend_status_message.c
  toxcore/net_crypto.c
  toxcore/tox.h
  toxcore/tox_events.h
  toxencryptsave/toxencryptsave.c
Labels: cleanup

#2090 refactor: Move `tox_new_log` to `auto_test_support`.
  auto_tests/auto_test_support.c
  auto_tests/auto_test_support.h
  auto_tests/conference_simple_test.c
  auto_tests/conference_two_test.c
  auto_tests/dht_test.c
  auto_tests/encryptsave_test.c
  auto_tests/file_saving_test.c
  auto_tests/file_transfer_test.c
  auto_tests/friend_request_test.c
  auto_tests/invalid_tcp_proxy_test.c
  auto_tests/invalid_udp_proxy_test.c
  auto_tests/lan_discovery_test.c
  auto_tests/messenger_test.c
  auto_tests/onion_test.c
  auto_tests/save_compatibility_test.c
  auto_tests/save_friend_test.c
  auto_tests/save_load_test.c
  auto_tests/set_name_test.c
  auto_tests/set_status_message_test.c
  auto_tests/tox_dispatch_test.c
  auto_tests/tox_events_test.c
  auto_tests/tox_many_tcp_test.c
  auto_tests/tox_many_test.c
  auto_tests/tox_one_test.c
  auto_tests/toxav_basic_test.c
  auto_tests/toxav_many_test.c
  testing/misc_tools.c
  testing/misc_tools.h
Labels: refactor

#2091 cleanup: Avoid casting function pointers.
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/tox.c
Labels: cleanup

#2096 cleanup: Return boolean constants, not ints from bool functions.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  testing/BUILD.bazel
  toxcore/DHT.c
  toxcore/LAN_discovery.c
  toxcore/TCP_connection.c
  toxcore/crypto_core.c
  toxcore/group.c
  toxcore/net_crypto.c
  toxcore/onion_client.c
  toxcore/tox.c
  toxencryptsave/toxencryptsave.c
Labels: cleanup

#2098 chore: remove DHT_test.c since it's unused
  CMakeLists.txt
  testing/BUILD.bazel
  testing/DHT_test.c
  testing/Makefile.inc
Labels: chore

#2097 cleanup: Remove implicit conversions from `uint32_t` to `bool`.
  toxav/bwcontroller.c
  toxav/msi.c
  toxav/rtp.c
  toxav/toxav.c
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/TCP_client.c
  toxcore/TCP_connection.c
  toxcore/TCP_server.c
  toxcore/group.c
  toxcore/list.c
  toxcore/net_crypto.c
Labels: cleanup

#2099 cleanup: Reduce name shadowing; remove ptr-to-bool conversions.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/LAN_discovery.c
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/TCP_common.c
  toxcore/logger.c
  toxcore/mono_time.c
  toxcore/network.c
  toxcore/onion_announce.c
  toxcore/onion_announce.h
  toxcore/onion_client.c
  toxcore/tox.c
Labels: cleanup

#2102 cleanup: Mark all local non-pointers as const where possible.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxav/audio.c
  toxav/bwcontroller.c
  toxav/groupav.c
  toxav/rtp.c
  toxav/toxav.c
  toxav/video.c
  toxcore/DHT.c
  toxcore/LAN_discovery.c
  toxcore/Messenger.c
  toxcore/TCP_client.c
  toxcore/TCP_connection.c
  toxcore/TCP_server.c
  toxcore/crypto_core.c
  toxcore/group.c
  toxcore/list.c
  toxcore/mono_time.c
  toxcore/net_crypto.c
  toxcore/network.c
  toxcore/onion.c
  toxcore/onion_announce.c
  toxcore/onion_client.c
  toxcore/tox.c
  toxcore/tox_api.c
  toxencryptsave/toxencryptsave.c
Labels: cleanup

#2100 chore: remove cpufeatures.c
  CMakeLists.txt
  other/cpufeatures.c
Labels: chore

#2105 cleanup: Change valid status of onion friend to bool.
  toxcore/onion_client.c
Labels: cleanup

#2092 perf: fix issue with friend finding taking too long after disconnects.
  toxcore/onion_client.c
Labels: performance

#2104 fix: Report failure to DHT bootstrap back to the client.
  .github/workflows/ci.yml
  auto_tests/dht_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxav/toxav.c
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/Messenger.c
  toxcore/friend_connection.c
  toxcore/network.c
  toxcore/onion_announce.c
  toxcore/onion_client.c
  toxcore/onion_client.h
  toxcore/tox.c
  toxcore/tox.h
Labels: bug

#2106 test: Add test coverage docker build for local tests.
  CMakeLists.txt
  auto_tests/Makefile.inc
  auto_tests/send_message_test.c
  auto_tests/tox_one_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/docker/coverage/Dockerfile
  other/docker/coverage/run
  other/docker/coverage/run_mallocfail
  other/docker/sources/Dockerfile
  toxcore/BUILD.bazel
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/mono_time_test.cc
  toxcore/tox_test.cc
Labels: test

#2113 cleanup: Remove superfluous parentheses on the rhs of assignments.
  toxav/msi.c
  toxcore/DHT.c
  toxcore/group.c
  toxcore/net_crypto.c
  toxcore/onion_client.c
Labels: cleanup

#2114 cleanup: Avoid creating invalid enum values.
  toxcore/tox.c
Labels: cleanup

#2108 test: Add mallocfail and proxy test to our coverage runs.
  .github/scripts/coverage-linux
  .github/scripts/flags-coverage.sh
  .github/scripts/upload-coverage
  .github/workflows/ci.yml
  CMakeLists.txt
  auto_tests/BUILD.bazel
  auto_tests/auto_test_support.c
  auto_tests/friend_request_spam_test.c
  auto_tests/messenger_test.c
  auto_tests/proxy_test.c
  other/analysis/gen-file.sh
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/websocket/websockify/websockify.go
  other/docker/coverage/Dockerfile
  other/docker/coverage/mallocfail.h
  other/docker/coverage/run_mallocfail
  other/docker/coverage/syscall_funcs.c
  other/docker/sources/Dockerfile
  other/proxy/BUILD.bazel
  other/proxy/proxy_server.go
  testing/misc_tools.c
  toxcore/TCP_client.c
  toxcore/TCP_common.c
  toxcore/TCP_server.c
  toxcore/ping_array_test.cc
Labels: test

#2117 cleanup: Comply with strict include ordering.
  toxcore/TCP_connection.h
  toxcore/crypto_core.c
  toxcore/tox.c
  toxcore/tox_api.c
Labels: cleanup

#2116 cleanup: Remove more boolean conversions (and a bugfix).
  auto_tests/TCP_test.c
  auto_tests/dht_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  testing/BUILD.bazel
  toxav/msi.c
  toxav/toxav.c
  toxcore/DHT.c
  toxcore/LAN_discovery.c
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/TCP_client.c
  toxcore/TCP_common.c
  toxcore/TCP_common.h
  toxcore/TCP_connection.c
  toxcore/TCP_server.c
  toxcore/crypto_core.c
  toxcore/crypto_core.h
  toxcore/friend_connection.c
  toxcore/friend_requests.c
  toxcore/group.c
  toxcore/net_crypto.c
  toxcore/network.c
  toxcore/onion_announce.c
  toxcore/onion_client.c
  toxcore/ping.c
  toxcore/tox.c
  toxcore/util.c
  toxcore/util.h
  toxcore/util_test.cc
Labels: cleanup

#2120 cleanup: Remove all boolean-int conversions.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/LAN_discovery.c
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/TCP_server.c
  toxcore/friend_connection.c
  toxcore/group.c
  toxcore/group.h
  toxcore/list.c
  toxcore/list.h
  toxcore/net_crypto.c
  toxcore/network.c
  toxcore/onion.c
  toxcore/onion_client.c
  toxcore/ping.c
  toxcore/tox.c
Labels: cleanup

#2115 cleanup: Log at ERROR level when `connect()` fails.
  auto_tests/TCP_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/TCP_client.c
  toxcore/network.c
  toxcore/network.h
  toxcore/onion.c
Labels: cleanup
