Repository TokTok/c-toxcore, pull requests merged in 2022-01, with the labels that each got.

#1834 cleanup: Reduce the scope of for-loop iterator variables.
  .github/settings.yml
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/Messenger.c
  toxcore/TCP_connection.c
  toxcore/TCP_server.c
  toxcore/net_crypto.c
  toxcore/onion_announce.c
  toxcore/onion_client.c
  toxcore/ping.c
Labels: cleanup

#1815 test: add ability for autotests to use TCP connections
  auto_tests/conference_av_test.c
  auto_tests/conference_double_invite_test.c
  auto_tests/conference_invite_merge_test.c
  auto_tests/conference_peer_nick_test.c
  auto_tests/conference_test.c
  auto_tests/friend_connection_test.c
  auto_tests/lossless_packet_test.c
  auto_tests/lossy_packet_test.c
  auto_tests/overflow_recvq_test.c
  auto_tests/overflow_sendq_test.c
  auto_tests/reconnect_test.c
  auto_tests/run_auto_test.h
  auto_tests/send_message_test.c
  auto_tests/typing_test.c
Labels: test

#1836 fix: possible unintended negative loop bound
  toxav/groupav.c
Labels: bug

#1835 cleanup: remove dead code
  .travis/cmake-windows.sh
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
Labels: cleanup

#1837 chore: Add bazel-debug build.
  .cirrus.yml
  .github/settings.yml
Labels: chore

#1840 chore: Remove old travis docker scripts.
  other/docker/cmake/Dockerfile
  other/docker/run-ci
  other/docker/travis/Dockerfile
Labels: chore

#1844 cleanup: make struct typedefs have the same name as their struct
  toxav/audio.h
  toxav/bwcontroller.c
  toxav/bwcontroller.h
  toxav/msi.h
  toxav/toxav.c
  toxav/video.h
Labels: cleanup

#1845 fix: use correct sample size in toxav_basic_test
  auto_tests/toxav_basic_test.c
Labels: bug

#1850 chore: Add a GH Actions code coverage job
  .github/workflows/ci.yml
  .travis/cmake-linux
Labels: chore

#1853 cleanup: Remove useless parentheses.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/Messenger.c
  toxcore/TCP_connection.c
  toxcore/group.c
  toxcore/list.c
  toxcore/net_crypto.c
  toxcore/onion.c
Labels: cleanup

#1860 cleanup: Fix `calloc` argument order.
  toxav/audio.c
  toxav/bwcontroller.c
  toxav/groupav.c
  toxav/msi.c
  toxav/ring_buffer.c
  toxav/toxav.c
  toxav/video.c
  toxcore/TCP_client.c
Labels: cleanup

#1861 cleanup: Use `calloc` instead of `malloc` for struct allocations.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/TCP_client.c
  toxcore/TCP_server.c
  toxcore/group.c
  toxcore/mono_time.c
  toxcore/net_crypto.c
  toxcore/network.c
  toxcore/ping_array.c
  toxcore/tox.c
  toxcore/tox_api.c
  toxencryptsave/toxencryptsave.c
Labels: cleanup

#1862 chore: Remove all references to Travis CI.
  .circleci/cmake-asan
  .circleci/cmake-tsan
  .github/scripts/autotools-linux
  .github/scripts/cmake-freebsd-stage2
  .github/scripts/cmake-linux
  .github/scripts/cmake-osx
  .github/scripts/cmake-win32
  .github/scripts/cmake-win64
  .github/scripts/cmake-windows.sh
  .github/scripts/flags-clang.sh
  .github/scripts/flags-gcc.sh
  .github/scripts/flags.sh
  .github/scripts/tox-bootstrapd-docker
  .github/scripts/upload-coverage
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  .travis.yml
  other/docker/autotools/Dockerfile
Labels: chore

#1867 chore: Retry asan/tsan tests a few more times.
  .circleci/cmake-asan
  .circleci/cmake-tsan
Labels: chore

#1870 chore: Disable the OpenMP cracker in bazel for now.
  .cirrus.yml
  other/fun/BUILD.bazel
Labels: chore

#1871 chore: Enable compiler layering check.
  other/bootstrap_daemon/BUILD.bazel
  testing/BUILD.bazel
  toxav/BUILD.bazel
  toxcore/BUILD.bazel
Labels: chore

#1865 cleanup: Remove extra parens around function arguments.
  other/analysis/gen-file.sh
  toxav/bwcontroller.c
  toxav/rtp.c
  toxcore/friend_connection.c
  toxcore/group.c
  toxcore/network.c
  toxcore/onion_client.c
  toxcore/state.c
Labels: cleanup

#1832 fix: a double-unlocking mutex in toxav
  toxav/audio.c
Labels: bug

#1873 chore: Enable layering check in all c-toxcore build files.
  BUILD.bazel
  auto_tests/BUILD.bazel
  other/BUILD.bazel
  other/fun/BUILD.bazel
  super_donators/BUILD.bazel
  toxcore/BUILD.bazel
  toxencryptsave/BUILD.bazel
Labels: chore

#1866 chore: Run tokstyle with 3 cores.
  testing/BUILD.bazel
  toxcore/Messenger.c
Labels: chore

#1874 cleanup: replace all instances of atoi with strtol
  other/DHT_bootstrap.c
  other/fun/BUILD.bazel
  other/fun/strkey.c
  testing/DHT_test.c
  testing/Messenger_test.c
Labels: cleanup

#1875 chore: Add asan/tsan bazel builds.
  .cirrus.yml
  testing/BUILD.bazel
Labels: chore

#1876 chore: Ignore some failures in bazel-tsan.
  .cirrus.yml
  .github/settings.yml
Labels: chore

#1877 fix: Fix some uninitialised memory errors found by valgrind.
  .circleci/config.yml
  .cirrus.yml
  .github/settings.yml
  .github/workflows/ci.yml
  BUILD.bazel
  auto_tests/conference_av_test.c
  auto_tests/encryptsave_test.c
  other/astyle/format-source
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxav/BUILD.bazel
  toxcore/BUILD.bazel
  toxcore/DHT.c
  toxcore/Messenger.c
  toxcore/crypto_core.c
  toxcore/crypto_core_test.cc
  toxcore/network.h
  toxcore/onion.c
  toxcore/onion_client.c
  toxcore/ping.c
  toxencryptsave/BUILD.bazel
Labels: bug

#1878 fix: don't count filetransfer as sending until accepted
  toxcore/Messenger.c
Labels: bug

#1841 cleanup: refactor toxav_call_control
  toxav/toxav.c
Labels: cleanup

#1880 chore: Run static analysers in multiple variants.
  .circleci/config.yml
  .cirrus.yml
  .github/settings.yml
  .restyled.yaml
  auto_tests/encryptsave_test.c
  other/analysis/gen-file.sh
  other/analysis/run-check-recursion
  other/analysis/run-clang
  other/analysis/run-clang-analyze
  other/analysis/run-clang-tidy
  other/analysis/run-cppcheck
  other/analysis/run-gcc
  other/analysis/run-infer
  other/analysis/variants.sh
  toxcore/crypto_core.c
Labels: chore

#1887 test: Add two more bootstrap/TCP nodes to autotests
  auto_tests/bootstrap_test.c
  auto_tests/run_auto_test.h
  auto_tests/tcp_relay_test.c
Labels: test

#1884 chore: Add mypy Python type check.
  .github/settings.yml
  .github/workflows/ci.yml
  .github/workflows/sonar-scan.yml
  other/analysis/check_recursion
  other/bootstrap_daemon/docker/get-nodes.py
  other/fun/bootstrap_node_info.py
  other/fun/make-funny-savefile.py
Labels: chore

#1891 cleanup: Remove our only use of sprintf.
  toxcore/Messenger.c
Labels: cleanup

#1889 cleanup: Stop using `strerror` directly.
  auto_tests/network_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxav/bwcontroller.c
  toxav/rtp.c
  toxav/toxav.c
  toxcore/TCP_client.c
  toxcore/network.c
  toxcore/network.h
Labels: cleanup

#1881 cleanup: Merge crypto_core and crypto_core_mem.
  CMakeLists.txt
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/BUILD.bazel
  toxcore/Makefile.inc
  toxcore/crypto_core.c
  toxcore/crypto_core_mem.c
Labels: cleanup

#1894 cleanup: Deduplicate a somewhat complex loop in DHT.c.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/network.c
  toxcore/network.h
  toxcore/onion_client.c
Labels: cleanup

#1898 cleanup: Use pointer cast instead of memcpy in qsort callback.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/onion_announce.c
  toxcore/onion_client.c
Labels: cleanup

#1899 cleanup: Make `Networking_Core` pointer-to-const where possible.
  .github/scripts/cmake-linux
  .github/scripts/cmake-osx
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/network.c
  toxcore/network.h
Labels: cleanup

#1901 cleanup: Make parameters pointers-to-const where possible.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/LAN_discovery.c
  toxcore/LAN_discovery.h
  toxcore/Messenger.c
  toxcore/TCP_client.c
  toxcore/TCP_client.h
  toxcore/TCP_connection.c
  toxcore/TCP_connection.h
  toxcore/TCP_server.c
  toxcore/TCP_server.h
  toxcore/friend_connection.c
  toxcore/friend_connection.h
  toxcore/group.c
  toxcore/group.h
  toxcore/net_crypto.c
  toxcore/net_crypto.h
  toxcore/onion_client.c
  toxcore/ping.c
Labels: cleanup

#1900 cleanup: Remove old check Suite compat layer.
  CMakeLists.txt
  auto_tests/Makefile.inc
  auto_tests/TCP_test.c
  auto_tests/check_compat.h
  auto_tests/crypto_test.c
  auto_tests/messenger_test.c
  auto_tests/network_test.c
  auto_tests/skeleton_test.c
  auto_tests/tox_many_tcp_test.c
  auto_tests/tox_strncasecmp_test.c
Labels: cleanup

#1903 cleanup: Even more pointer-to-const parameters.
  .circleci/cmake-asan
  .circleci/cmake-tsan
  toxav/groupav.c
  toxav/groupav.h
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/LAN_discovery.c
  toxcore/TCP_connection.c
  toxcore/TCP_connection.h
  toxcore/friend_connection.c
  toxcore/group.c
  toxcore/net_crypto.c
  toxcore/net_crypto.h
  toxcore/onion.c
  toxcore/onion.h
  toxcore/onion_announce.c
  toxcore/onion_announce.h
  toxcore/onion_client.c
Labels: cleanup

#1906 cleanup: Split large switch statement into functions.
  toxcore/net_crypto.c
Labels: cleanup

#1905 chore: Mark unsafe code as testonly.
  other/BUILD.bazel
  other/fun/BUILD.bazel
  testing/BUILD.bazel
Labels: chore

#1897 refactor: Deduplicate a bunch of code in TCP client/server.
  CMakeLists.txt
  auto_tests/BUILD.bazel
  auto_tests/TCP_test.c
  other/BUILD.bazel
  other/bootstrap_daemon/BUILD.bazel
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/BUILD.bazel
  toxcore/Makefile.inc
  toxcore/Messenger.h
  toxcore/TCP_client.c
  toxcore/TCP_client.h
  toxcore/TCP_common.c
  toxcore/TCP_common.h
  toxcore/TCP_connection.h
  toxcore/TCP_server.c
  toxcore/TCP_server.h
  toxcore/net_crypto.c
Labels: refactor

#1909 chore: Expose public API headers as files in bazel.
  BUILD.bazel
Labels: chore

#1912 cleanup: Remove uses of `strcpy` and `sprintf`.
  .github/workflows/sonar-scan.yml
  other/DHT_bootstrap.c
  other/analysis/run-clang-tidy
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/src/config.c
  other/bootstrap_daemon/src/tox-bootstrapd.c
  other/bootstrap_node_packets.c
  other/bootstrap_node_packets.h
  testing/BUILD.bazel
Labels: cleanup

#1910 cleanup: Remove our only use of flexible array members in toxcore.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/TCP_common.c
  toxcore/TCP_common.h
  toxcore/TCP_server.c
  toxcore/group.c
  toxcore/network.c
Labels: cleanup

#1915 cleanup: replace magic numbers with appropriately named constants
  toxcore/TCP_client.c
Labels: cleanup

#1916 chore: Add a make_single_file script, used for CI.
  .github/workflows/ci.yml
  other/make_single_file
Labels: chore

#1917 fix: buffer overwrite in bootstrap config
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/src/config.c
Labels: bug

#1918 chore: Run sonar scan on pull requests.
  .github/workflows/sonar-scan.yml
Labels: chore

#1914 chore: Add cpplint to the CI.
  .circleci/config.yml
  .github/settings.yml
  other/analysis/run-cpplint
  other/bootstrap_daemon/src/config.c
  other/fun/cracker.c
  other/fun/minimal-save-generator.c
  other/fun/sign.c
  other/fun/strkey.c
  toxav/audio.h
  toxav/groupav.h
  toxav/msi.c
  toxav/msi.h
  toxav/ring_buffer.c
  toxav/rtp.h
  toxav/toxav.c
  toxav/video.h
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/net_crypto.c
  toxcore/net_crypto.h
  toxcore/network.c
  toxcore/network.h
  toxcore/ping.h
  toxcore/ping_array.h
  toxcore/tox_api.c
  toxencryptsave/toxencryptsave.c
Labels: chore

#1920 cleanup: refactor group audio packet data handling
  toxav/groupav.c
Labels: cleanup

#1924 test: refactor autotest live network bootstrapping
  .circleci/config.yml
  .github/scripts/flags-gcc.sh
  auto_tests/bootstrap_test.c
  auto_tests/run_auto_test.h
  auto_tests/tcp_relay_test.c
Labels: test

#1926 fix: group av memory leak
  toxav/groupav.c
Labels: bug

#1923 fix: corruption in key files, making it unable to load when node starts.
  other/DHT_bootstrap.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/src/tox-bootstrapd.c
  other/fun/save-generator.c
Labels: bug

#1818 feat: Add programs for creating savedata & bootstrap keys
  INSTALL.md
  other/analysis/gen-file.sh
  other/fun/BUILD.bazel
  other/fun/create_bootstrap_keys.c
  other/fun/create_common.h
  other/fun/create_minimal_savedata.c
  other/fun/create_savedata.c
  other/fun/minimal-save-generator.c
Labels: enhancement

#1933 chore: Add a Bazel Buildifier CI job
  .github/workflows/ci.yml
  auto_tests/BUILD.bazel
  other/fun/BUILD.bazel
Labels: chore

#1929 cleanup: make some non-const pointers const
  toxav/groupav.c
  toxcore/LAN_discovery.c
  toxcore/Messenger.c
  toxcore/TCP_connection.c
  toxcore/TCP_server.c
  toxcore/friend_connection.c
  toxcore/group.c
  toxcore/net_crypto.c
  toxcore/network.c
  toxcore/onion_announce.c
  toxcore/onion_client.c
Labels: cleanup

#1937 cleanup: remove brackets from ip_ntoa ipv6 formatting
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/LAN_discovery.c
  toxcore/network.c
  toxcore/network.h
  toxcore/network_test.cc
Labels: cleanup

#1938 cleanup: small refactor of DHT getnodes function
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/DHT.h
Labels: cleanup

#1939 chore: Rename bazel-release to -opt and -debug to -dbg.
  .cirrus.yml
  .github/settings.yml
Labels: chore

#1940 chore: Use latest instead of versioned toktok-stack image.
  .cirrus.yml
Labels: chore

#1942 cleanup: Add some toxav bounds/sanity checks
  toxav/audio.c
  toxav/rtp.c
Labels: cleanup
