Repository TokTok/c-toxcore, pull requests merged in 2022-04, with the labels that each got.

#2225 fix: fix typo in git command in INSTALL.md
  INSTALL.md
Labels: bug

#2214 cleanup: Remove all uses of `TOX_*_MAX_SIZE` macros.
  auto_tests/file_saving_test.c
  auto_tests/lossless_packet_test.c
  auto_tests/lossy_packet_test.c
  auto_tests/save_compatibility_test.c
  auto_tests/save_friend_test.c
  auto_tests/send_message_test.c
  other/fun/save-generator.c
  toxcore/tox_test.cc
Labels: cleanup

#2213 cleanup: Remove unused random_testing program.
  other/analysis/run-cppcheck
  testing/BUILD.bazel
  testing/CMakeLists.txt
  testing/random_testing.cc
Labels: cleanup

#2217 cleanup: Add Network object parameter for addr_resolve.
  auto_tests/network_test.c
  auto_tests/onion_test.c
  other/DHT_bootstrap.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/src/tox-bootstrapd.c
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/Messenger.c
  toxcore/network.c
  toxcore/network.h
  toxcore/tox.c
Labels: cleanup

#2219 refactor: Rename bin_pack/unpack functions the same as cmp funcs.
  toxcore/bin_pack.c
  toxcore/bin_pack.h
  toxcore/bin_pack_test.cc
  toxcore/bin_unpack.c
  toxcore/bin_unpack.h
  toxcore/events/conference_invite.c
  toxcore/events/conference_message.c
  toxcore/events/conference_peer_name.c
  toxcore/events/conference_title.c
  toxcore/events/file_recv.c
  toxcore/events/file_recv_chunk.c
  toxcore/events/friend_lossless_packet.c
  toxcore/events/friend_lossy_packet.c
  toxcore/events/friend_message.c
  toxcore/events/friend_name.c
  toxcore/events/friend_request.c
  toxcore/events/friend_status_message.c
Labels: refactor

#2227 cleanup: Disallow stack frames of over 9000 bytes.
  .github/scripts/flags-gcc.sh
  auto_tests/TCP_test.c
  auto_tests/crypto_test.c
  other/analysis/run-gcc
Labels: cleanup

#2228 chore: Fix path to fuzzer binaries in clusterfuzz build.
  .clusterfuzzlite/build.sh
Labels: chore

#2229 cleanup: Remove layers in the cmake build.
  CMakeLists.txt
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
Labels: cleanup

#2238 cleanup: Make `*_free` and `kill_*` functions nullable.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/Messenger.h
  toxcore/TCP_connection.c
  toxcore/TCP_connection.h
  toxcore/TCP_server.c
  toxcore/TCP_server.h
  toxcore/bin_pack.h
  toxcore/friend_connection.h
  toxcore/friend_requests.h
  toxcore/group.c
  toxcore/group.h
  toxcore/list.c
  toxcore/list.h
  toxcore/logger.h
  toxcore/mono_time.c
  toxcore/mono_time.h
  toxcore/net_crypto.c
  toxcore/net_crypto.h
  toxcore/network.h
  toxcore/onion.h
  toxcore/onion_announce.h
  toxcore/onion_client.h
  toxcore/ping.h
  toxcore/ping_array.h
Labels: cleanup

#2236 chore: Add dependabot config.
  .github/dependabot.yml
Labels: chore

#2232 test: Add fuzzer support functions for internal toxcore objects.
  testing/fuzzing/BUILD.bazel
  testing/fuzzing/fuzz_support.cc
  testing/fuzzing/fuzz_support.h
  testing/fuzzing/fuzz_tox.h
  toxcore/DHT_fuzz_test.cc
  toxcore/group_moderation_fuzz_test.cc
Labels: test

#2242 cleanup: Use `static_assert` instead of `assert` where possible.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  testing/BUILD.bazel
  toxcore/Messenger.c
  toxcore/network.c
Labels: cleanup

#2249 test: Improve stability of forwarding_test.
  auto_tests/forwarding_test.c
Labels: test

#2244 refactor: Allow NULL logger; make it no-op in NDEBUG.
  .github/scripts/flags-clang.sh
  CMakeLists.txt
  INSTALL.md
  other/analysis/run-clang
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/logger.c
  toxcore/logger.h
Labels: refactor

#2248 refactor: Use a struct for the `ip_ntoa` buffer.
  auto_tests/network_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/Messenger.c
  toxcore/network.c
  toxcore/network.h
  toxcore/network_test.cc
  toxcore/tox.c
Labels: refactor

#2250 cleanup: remove populate_path_nodes_tcp
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/network.c
  toxcore/onion_client.c
Labels: cleanup

#2246 fix: Don't crash if RNG init failed.
  other/analysis/run-gcc
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxencryptsave/toxencryptsave.c
  toxencryptsave/toxencryptsave.h
Labels: bug

#2206 feat: Allow overriding mono_time in tox_new.
  auto_tests/TCP_test.c
  auto_tests/announce_test.c
  auto_tests/auto_test_support.c
  auto_tests/forwarding_test.c
  auto_tests/lan_discovery_test.c
  auto_tests/onion_test.c
  auto_tests/save_load_test.c
  auto_tests/tox_events_test.c
  auto_tests/toxav_many_test.c
  other/DHT_bootstrap.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/src/tox-bootstrapd.c
  testing/Messenger_test.c
  testing/fuzzing/BUILD.bazel
  testing/fuzzing/bootstrap_harness.cc
  testing/fuzzing/fuzz_support.cc
  testing/fuzzing/fuzz_support.h
  testing/fuzzing/toxsave_harness.cc
  toxav/toxav.c
  toxcore/mono_time.c
  toxcore/mono_time.h
  toxcore/mono_time_test.cc
  toxcore/ping_array_test.cc
  toxcore/tox.c
  toxcore/tox.h
  toxcore/tox_api.c
  toxcore/tox_private.c
  toxcore/tox_private.h
Labels: enhancement

#2233 cleanup: Replace a series of `if` statements with a `switch`.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/Messenger.c
Labels: cleanup

#2255 fix: Fix a stack overflow triggered by small DHT packets.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/announce.c
Labels: bug

#2257 fix: Format IP as string again in error log.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/network.c
Labels: bug

#2251 chore: Add MISRA-2012 check using cppcheck's misra addon.
  .github/workflows/ci.yml
  other/docker/misra/.gitignore
  other/docker/misra/Dockerfile
  other/docker/misra/Makefile
  other/docker/misra/run
  toxav/msi.c
Labels: chore

#2243 chore: Add initial ESP32 docker build.
  .github/workflows/docker.yml
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/docker/esp32/CMakeLists.txt
  other/docker/esp32/Dockerfile
  other/docker/esp32/hello/CMakeLists.txt
  other/docker/esp32/hello/hello_main.c
  other/docker/esp32/run
  other/docker/esp32/toxcore/CMakeLists.txt
  other/docker/esp32/toxcore/toxcore_main.cc
  toxcore/mono_time.c
  toxcore/network.c
Labels: chore

#2258 refactor: Rename announce functions into their own namespace.
  auto_tests/announce_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/announce.c
  toxcore/announce.h
Labels: refactor

#2261 refactor: Protect array unpacking against invalid lengths.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/bin_pack_test.cc
  toxcore/bin_unpack.c
Labels: refactor

#2263 chore: Upgrade to C++20 in CMake build.
  CMakeLists.txt
Labels: chore

#2234 test: Add more functionality to the bootstrap fuzz harness.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  testing/fuzzing/BUILD.bazel
  testing/fuzzing/CMakeLists.txt
  testing/fuzzing/bootstrap_harness.cc
  testing/fuzzing/fuzz_adapter.c
  testing/fuzzing/fuzz_adapter.h
  testing/fuzzing/fuzz_support.cc
  testing/fuzzing/fuzz_support.h
  testing/fuzzing/toxsave_harness.cc
  toxcore/BUILD.bazel
  toxcore/ccompat.h
  toxcore/crypto_core.c
  toxcore/network.c
Labels: test

#2266 fix: Fixed leak and overrun added in e49a477a
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
Labels: bug

#2270 test: Improve error messages in toxav_basic_test.
  auto_tests/toxav_basic_test.c
Labels: test

#2272 fix: Add missing return on error
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/group_announce.c
Labels: bug, security

#2273 fix: Really fix overrun added in e49a477a
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/DHT_test.cc
Labels: bug

#2275 chore: Downgrade C++ version to 17
  CMakeLists.txt
  testing/fuzzing/fuzz_support.cc
Labels: chore

#2277 refactor: Avoid `static_cast` in `Fuzz_System` functions.
  testing/fuzzing/BUILD.bazel
  testing/fuzzing/CMakeLists.txt
  testing/fuzzing/func_conversion.h
  testing/fuzzing/fuzz_support.cc
Labels: refactor

#2283 fix: Allow onion paths to be built from more random nodes.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/crypto_core.c
Labels: bug

#2285 test: Don't abort fuzz test when tox_new fails.
  testing/fuzzing/bootstrap_harness.cc
Labels: test

#2282 fix: Fix potential array out-of-bounds in DHT onion path building.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  testing/fuzzing/bootstrap_harness.cc
  toxcore/DHT.c
Labels: bug

#2284 refactor: Move crypto utilities from util to crypto_core.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/BUILD.bazel
  toxcore/crypto_core.c
  toxcore/crypto_core.h
  toxcore/onion_announce.c
  toxcore/util.c
  toxcore/util.h
Labels: refactor

#2287 fix: Don't allow onion paths to be built from real friends.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/DHT.h
Labels: bug

#2279 test: Enable fuzzing for TCP.
  .github/scripts/coverage-linux
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/proxy/go.mod
  other/proxy/go.sum
  testing/fuzzing/bootstrap_harness.cc
  testing/fuzzing/fuzz_support.cc
  toxcore/TCP_client.c
  toxcore/network.c
Labels: test

#2288 test: enable additional sanitizers for fuzzing
  .github/workflows/cflite_batch.yml
Labels: test

#2289 test: Add a Null_System used in toxsave_harness.
  testing/fuzzing/fuzz_support.cc
  testing/fuzzing/fuzz_support.h
  testing/fuzzing/toxsave_harness.cc
Labels: test

#2281 cleanup: Avoid goto in msi.c.
  toxav/msi.c
Labels: cleanup

#2297 cleanup: remove unused field last_seen from Onion_Friend
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/onion_client.c
  toxcore/onion_client.h
Labels: cleanup

#2299 fix: remove the assert because buffer can be larger than UINT16_MAX.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/network.c
Labels: bug

#2300 chore: Release 0.2.18
  CHANGELOG.md
  CMakeLists.txt
  configure.ac
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  so.version
  toxcore/tox.h
Labels: chore
