Repository TokTok/c-toxcore, pull requests merged in 2022-03, with the labels that each got.

#2122 chore: Enable a bunch more warnings in GCC builds.
  .github/scripts/flags-gcc.sh
  toxcore/ccompat.h
Labels: chore

#2123 cleanup: Remove some more implicit bool conversions.
  toxav/rtp.c
  toxcore/LAN_discovery.c
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/TCP_server.c
  toxcore/network.c
  toxcore/network.h
  toxcore/onion_announce.c
  toxcore/onion_announce.h
  toxcore/ping_array.c
  toxcore/tox.c
Labels: cleanup

#2126 cleanup: Remove port from `Broadcast_Info`.
  auto_tests/auto_test_support.c
  auto_tests/lan_discovery_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/docker/coverage/run_mallocfail
  toxcore/LAN_discovery.c
  toxcore/tox_test.cc
Labels: cleanup

#2127 cleanup: Remove `EAGAIN` from the list of ignored errors.
  toxcore/network.c
Labels: cleanup

#2128 test: Add unit test for create/handle request packets.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/DHT_test.cc
Labels: test

#2133 cleanup: Remove redundant Messenger and DHT tests.
  .cirrus.yml
  CMakeLists.txt
  auto_tests/BUILD.bazel
  auto_tests/Makefile.inc
  auto_tests/dht_test.c
  auto_tests/messenger_test.c
  other/analysis/gen-file.sh
  other/emscripten/Dockerfile
  toxcore/BUILD.bazel
Labels: cleanup

#2135 cleanup: Move test-only functions into tests.
  auto_tests/onion_test.c
  auto_tests/tox_dispatch_test.c
  other/DHT_bootstrap.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/src/tox-bootstrapd.c
  toxcore/network.c
  toxcore/network.h
  toxcore/onion.c
  toxcore/onion.h
  toxcore/tox_dispatch.c
Labels: cleanup

#2130 cleanup: Remove redundant `()` around `return` expression.
  toxcore/group.c
  toxcore/net_crypto.c
  toxcore/onion_client.c
Labels: cleanup

#2132 cleanup: Remove dependency from LAN_discovery onto DHT.
  auto_tests/onion_test.c
  other/BUILD.bazel
  other/DHT_bootstrap.c
  other/bootstrap_daemon/BUILD.bazel
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/src/tox-bootstrapd.c
  toxcore/BUILD.bazel
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/LAN_discovery.c
  toxcore/LAN_discovery.h
  toxcore/Messenger.c
  toxcore/friend_connection.c
Labels: cleanup

#2136 docs: Clean up doxygen comments to be more doxygen-like.
  .github/workflows/ci.yml
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/docker/cimplefmt/Dockerfile
  other/docker/cimplefmt/run
  toxav/groupav.c
  toxav/groupav.h
  toxav/ring_buffer.c
  toxav/rtp.c
  toxav/rtp.h
  toxav/toxav.h
  toxav/toxav_old.c
  toxav/video.c
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/LAN_discovery.c
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/TCP_client.c
  toxcore/TCP_client.h
  toxcore/TCP_common.c
  toxcore/TCP_common.h
  toxcore/TCP_connection.c
  toxcore/TCP_connection.h
  toxcore/TCP_server.c
  toxcore/TCP_server.h
  toxcore/crypto_core.h
  toxcore/friend_connection.c
  toxcore/friend_connection.h
  toxcore/friend_requests.c
  toxcore/friend_requests.h
  toxcore/group.c
  toxcore/group.h
  toxcore/list.c
  toxcore/list.h
  toxcore/mono_time.h
  toxcore/net_crypto.c
  toxcore/net_crypto.h
  toxcore/network.c
  toxcore/network.h
  toxcore/onion.c
  toxcore/onion.h
  toxcore/onion_announce.c
  toxcore/onion_announce.h
  toxcore/onion_client.c
  toxcore/onion_client.h
  toxcore/ping.c
  toxcore/ping.h
  toxcore/ping_array.c
  toxcore/tox.h
  toxcore/tox_events.h
  toxcore/util.c
  toxcore/util.h
  toxencryptsave/toxencryptsave.h
Labels: documentation

#2138 chore: Release 0.2.17
  CHANGELOG.md
  CMakeLists.txt
  configure.ac
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  so.version
  toxcore/tox.h
Labels: chore

#2140 cleanup: Add assertion for decrypted data length.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/TCP_client.c
Labels: cleanup

#2141 cleanup: Disable LAN discovery in TCP-only mode.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/network.c
  toxcore/tox.c
Labels: cleanup

#2142 cleanup: Count re-adding an existing bootstrap node as success.
  auto_tests/save_load_test.c
  toxcore/onion_client.c
  toxcore/onion_client.h
  toxcore/tox.c
  toxcore/tox_test.cc
Labels: cleanup

#2144 cleanup: Minor cleanups in TCP_connection.c.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/TCP_connection.c
  toxcore/tox.c
Labels: cleanup

#2143 fix: Allow port range in DHT_bootstrap.c.
  other/DHT_bootstrap.c
Labels: bug

#2146 chore: Add testing/Dockerfile to the CI build.
  .github/workflows/docker.yml
Labels: chore

#2145 chore: Be even more explicit about integer range bounds.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
Labels: chore

#2150 cleanup: Move all the group.h structs into group.c.
  toxav/groupav.c
  toxcore/group.c
  toxcore/group.h
Labels: cleanup

#2153 docs: Put all the tox public api into a fake "tox" namespace.
  toxcore/tox.h
Labels: documentation

#2155 fix: Eliminate memory leak in toxav.
  toxav/rtp.c
Labels: bug

#2156 cleanup: Sync doc comments between .h and .c files.
  toxcore/Messenger.c
  toxcore/TCP_connection.c
  toxcore/TCP_connection.h
  toxcore/group.h
  toxcore/util.c
Labels: cleanup

#2154 test: Speed up toxav_many_test by using fake mono_time.
  auto_tests/toxav_many_test.c
Labels: test

#2163 chore: Enable memory sanitizer build.
  .circleci/config.yml
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
Labels: chore

#2157 cleanup: Split the huge TCP client packet handler.
  other/analysis/run-cppcheck
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/TCP_client.c
  toxencryptsave/toxencryptsave.c
Labels: cleanup

#2160 test: Improve the stability of the save_load test
  auto_tests/save_load_test.c
Labels: test

#2149 cleanup: Avoid `memset` on structs.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  testing/BUILD.bazel
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/Messenger.c
  toxcore/TCP_connection.c
  toxcore/friend_connection.c
  toxcore/group.c
  toxcore/network.c
  toxcore/network.h
  toxcore/onion_client.c
Labels: cleanup

#2164 feat: Merge onion_announce changes from new groupchats fork
  .github/scripts/flags-clang.sh
  .github/scripts/flags-gcc.sh
  auto_tests/onion_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/network.c
  toxcore/network.h
  toxcore/onion.c
  toxcore/onion_announce.c
  toxcore/onion_announce.h
  toxcore/onion_client.c
Labels: enhancement

#2166 cleanup: Reduce scope of variables as requested by cimple.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxav/bwcontroller.c
  toxav/video.c
  toxcore/DHT.c
  toxcore/group.c
Labels: cleanup

#2167 cleanup: Reduce scope of array-typed variables where possible.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  testing/BUILD.bazel
  toxcore/Messenger.c
  toxcore/network.c
Labels: cleanup

#2173 chore: Use "master" as the branch in toktok-fuzzer.
  .github/workflows/cflite_batch.yml
  .github/workflows/cflite_cron.yml
Labels: chore

#2170 test: Add fuzzer tests to the bazel build.
  .cirrus.yml
  .clang-format
  other/analysis/gen-file.sh
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/websocket/websockify/BUILD.bazel
  testing/fuzzing/BUILD.bazel
  testing/fuzzing/bootstrap_harness.cc
  testing/fuzzing/fuzz_adapter.c
  testing/fuzzing/toxsave_harness.cc
  toxcore/BUILD.bazel
  toxcore/DHT_fuzz_test.cc
  toxcore/logger.h
  toxcore/network.c
  toxcore/tox_events.c
  toxcore/tox_events_fuzz_test.cc
  toxcore/tox_events_test.cc
Labels: test

#2176 test: try to save the fuzzed save file again
  testing/fuzzing/toxsave_harness.cc
Labels: test

#2158 cleanup: Expose `struct Tox` to internal code.
  auto_tests/TCP_test.c
  auto_tests/auto_test_support.c
  auto_tests/auto_test_support.h
  auto_tests/lan_discovery_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxav/BUILD.bazel
  toxav/toxav.c
  toxav/toxav_old.c
  toxcore/BUILD.bazel
  toxcore/Makefile.inc
  toxcore/Messenger.c
  toxcore/network.c
  toxcore/tox.c
  toxcore/tox_struct.h
Labels: cleanup

#2182 test: Improve stability of tox_many_tcp_test.
  auto_tests/tox_many_tcp_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/TCP_server.c
Labels: test

#2101 cleanup: improve CMakeLists.txt structure
  .circleci/cmake-asan
  CMakeLists.txt
  INSTALL.md
  auto_tests/CMakeLists.txt
  other/bootstrap_daemon/CMakeLists.txt
  other/bootstrap_daemon/docker/Dockerfile
  other/fun/CMakeLists.txt
  testing/CMakeLists.txt
  testing/fuzzing/CMakeLists.txt
Labels: cleanup

#2186 cleanup: Use `_Static_assert` in gcc/clang.
  .github/scripts/cmake-osx
  toxcore/ccompat.h
Labels: cleanup

#2184 test: Add some support functions to make writing fuzzers easier.
  testing/fuzzing/BUILD.bazel
  testing/fuzzing/fuzz_support.cc
  testing/fuzzing/fuzz_support.h
  toxcore/BUILD.bazel
  toxcore/DHT_fuzz_test.cc
Labels: test

#2188 cleanup: Make addr_resolve a private function.
  auto_tests/network_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/network.c
  toxcore/network.h
Labels: cleanup

#2189 chore: Add third_party to toxcore-sources docker image.
  other/docker/sources/Dockerfile
Labels: chore

#2183 test: Enable more tests for msan.
  .circleci/config.yml
Labels: test

#2193 perf: Make time move a lot faster in fuzzing runs.
  testing/fuzzing/BUILD.bazel
  testing/fuzzing/bootstrap_harness.cc
  testing/fuzzing/fuzz_adapter.c
  testing/fuzzing/fuzz_adapter.h
  toxcore/mono_time.c
Labels: performance

#2196 test: Remove save_load_test from autotools build.
  auto_tests/Makefile.inc
Labels: test

#2200 cleanup: Add more null checks in `tox_new`.
  toxcore/tox.c
Labels: cleanup

#2202 cleanup: Avoid name clash between struct field and function.
  toxcore/Messenger.c
Labels: cleanup

#2199 cleanup: Mark Mono_Time const where possible.
  auto_tests/onion_test.c
  toxcore/onion.c
  toxcore/onion.h
  toxcore/onion_announce.c
  toxcore/onion_announce.h
  toxcore/onion_client.c
  toxcore/onion_client.h
Labels: cleanup

#2208 chore: Remove valgrind build.
  .cirrus.yml
  .github/settings.yml
Labels: chore

#2177 feat: Add support for overriding network functions.
  auto_tests/TCP_test.c
  auto_tests/auto_test_support.c
  auto_tests/onion_test.c
  other/DHT_bootstrap.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/bootstrap_daemon/src/tox-bootstrapd.c
  testing/Messenger_test.c
  toxcore/LAN_discovery.c
  toxcore/LAN_discovery.h
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/TCP_client.c
  toxcore/TCP_client.h
  toxcore/TCP_common.c
  toxcore/TCP_common.h
  toxcore/TCP_connection.c
  toxcore/TCP_connection.h
  toxcore/TCP_server.c
  toxcore/TCP_server.h
  toxcore/attributes.h
  toxcore/friend_connection.c
  toxcore/friend_connection.h
  toxcore/net_crypto.c
  toxcore/net_crypto.h
  toxcore/network.c
  toxcore/network.h
  toxcore/tox.c
  toxcore/tox_private.h
  toxcore/tox_struct.h
Labels: enhancement

#2187 test: Add DHT and tox_events fuzz tests to the cmake build.
  testing/fuzzing/CMakeLists.txt
Labels: test

#2210 chore: Clone submodules in clusterfuzzlite Dockerfile.
  .clusterfuzzlite/Dockerfile
  .github/workflows/docker.yml
  other/docker/tokstyle/Dockerfile
Labels: chore

#2169 feat: Merge moderation portion of new groupchats codebase
  CMakeLists.txt
  other/analysis/run-cppcheck
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/docker/coverage/Dockerfile
  testing/BUILD.bazel
  toxcore/BUILD.bazel
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/Messenger.c
  toxcore/crypto_core.c
  toxcore/crypto_core.h
  toxcore/crypto_core_test.cc
  toxcore/group_moderation.c
  toxcore/group_moderation.h
  toxcore/group_moderation_fuzz_test.cc
  toxcore/group_moderation_test.cc
  toxcore/util.c
  toxcore/util.h
Labels: enhancement

#2212 cleanup: Expand `CONST_FUNCTION` and remove the macro.
  toxcore/tox_api.c
  toxcore/tox_test.cc
Labels: cleanup

#2211 cleanup: Move definitions of tox_private.h functions to tox_private.c.
  CMakeLists.txt
  toxcore/BUILD.bazel
  toxcore/Makefile.inc
  toxcore/tox.c
  toxcore/tox_private.c
  toxcore/tox_private.h
Labels: cleanup
