Repository TokTok/c-toxcore, pull requests merged in 2023-11, with the labels that each got.

#2414 fix: inversed return values
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/group_chats.c
Labels: bug

#2311 cleanup: make it more clear that assert and uint32_t increment both only exist if NDEBUG is not defined
  toxcore/DHT.c
Labels: cleanup

#2357 feat: get the number of close dht nodes with announce/store support
  auto_tests/dht_getnodes_api_test.c
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/tox_private.c
  toxcore/tox_private.h
Labels: diagnostic

#2354 fix: DHTBootstrap should always respond to version packets with toxcore version
  other/BUILD.bazel
  other/DHT_bootstrap.c
Labels: bug

#1944 chore: tox_new() should return null when savedata loading fails
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/tox.c
  toxcore/tox.h
Labels: api break, chore

#2203 refactor: Store time in Mono_Time in milliseconds.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  toxcore/mono_time.c
  toxcore/mono_time.h
Labels: refactor
