Repository TokTok/c-toxcore, pull requests merged in 2024-12, with the labels that each got.

#2803 cleanup: Fix layering check warnings.
  auto_tests/BUILD.bazel
  other/BUILD.bazel
  other/bootstrap_daemon/BUILD.bazel
  other/docker/esp32/BUILD.bazel
  super_donators/BUILD.bazel
  testing/fuzzing/BUILD.bazel
  testing/fuzzing/fuzz_support.cc
  toxcore/BUILD.bazel
Labels: cleanup

#2804 test: Fix crypto_test to initialise its plain text buffer.
  auto_tests/crypto_test.c
Labels: test

#2638 refactor: Use `merge_sort` instead of `qsort` for sorting.
  .circleci/config.yml
  CMakeLists.txt
  other/analysis/gen-file.sh
  other/docker/modules/check
  other/docker/modules/modules.Dockerfile
  toxcore/BUILD.bazel
  toxcore/DHT.c
  toxcore/Makefile.inc
  toxcore/crypto_core_test.cc
  toxcore/group.c
  toxcore/onion_announce.c
  toxcore/onion_client.c
  toxcore/sort.c
  toxcore/sort.h
  toxcore/sort_bench.cc
  toxcore/sort_test.cc
  toxcore/sort_test_util.cc
  toxcore/sort_test_util.hh
  toxcore/util.c
  toxcore/util_test.cc
Labels: refactor

#2805 chore: Fix tsan build by moving it to github ci.
  .circleci/config.yml
  .github/workflows/ci.yml
  other/docker/circleci/Dockerfile
  other/docker/circleci/entrypoint.sh
  other/docker/circleci/run
Labels: chore

#2801 fix: reduce memory usage in group chats by 75%
  toxcore/group_common.h
Labels: bug

#2807 fix: Allow peers to reconnect to group chats using a password
  auto_tests/group_general_test.c
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/tox.c
  toxcore/tox.h
Labels: bug

#2809 chore: Upgrade dependencies for websockify.
  other/bootstrap_daemon/websocket/websockify/go.mod
Labels: chore

#2811 cleanup: Remove redundant code for checking if group exists
  toxcore/group_chats.c
Labels: cleanup

#2812 docs: Output the error code string instead of int in toxav logging
  .cirrus.yml
  toxav/rtp.c
Labels: documentation

#2814 chore: Add dispatch/events headers to bazel export.
  BUILD.bazel
  toxcore/BUILD.bazel
Labels: chore

#2815 refactor: Use tox Memory for group allocations.
  .circleci/config.yml
  .cirrus.yml
  toxcore/group.c
Labels: refactor
