Repository TokTok/c-toxcore, pull requests merged in 2024-11, with the labels that each got.

#2651 refactor: Make ToxAV independent of toxcore internals.
  CMakeLists.txt
  auto_tests/toxav_many_test.c
  other/analysis/run-cppcheck
  toxav/BUILD.bazel
  toxav/Makefile.inc
  toxav/audio.c
  toxav/bwcontroller.c
  toxav/bwcontroller.h
  toxav/msi.c
  toxav/msi.h
  toxav/rtp.c
  toxav/rtp.h
  toxav/toxav.c
  toxav/toxav.h
  toxav/toxav_hacks.h
  toxav/video.c
  toxav/video.h
  toxcore/BUILD.bazel
  toxcore/Messenger.c
  toxcore/Messenger.h
  toxcore/net_crypto.c
  toxcore/net_crypto.h
  toxcore/tox.c
  toxcore/tox.h
Labels: toxav, refactor

#2783 fix: Return an error instead of crashing on nullptr args in NGC.
  toxcore/tox.c
  toxcore/tox.h
  toxcore/tox_api.c
Labels: bug

#2784 chore: lower cirrus ci timeout drastically
  .cirrus.yml
Labels: chore

#2786 cleanup: Fix all `-Wsign-compare` warnings.
  .github/scripts/flags-clang.sh
  .github/scripts/flags-gcc.sh
  auto_tests/conference_av_test.c
  auto_tests/conference_double_invite_test.c
  auto_tests/conference_invite_merge_test.c
  other/analysis/run-clang
  other/bootstrap_daemon/src/tox-bootstrapd.c
  other/fun/save-generator.c
  other/fun/sign.c
  other/fun/strkey.c
  toxav/groupav.c
  toxcore/DHT.c
  toxcore/announce.c
  toxcore/group.c
  toxcore/group_chats.c
  toxcore/onion_client.c
  toxencryptsave/toxencryptsave.c
Labels: cleanup

#2772 fix: friend_connections leak on allocation failure.
  toxcore/friend_connection.c
Labels: bug, P3

#2754 docs(toxav): fix docs of toxav.h
  toxav/toxav.h
Labels: toxav, documentation

#2782 fix(toxav): pass video bit rate as kbit
  toxav/toxav.c
Labels: bug, toxav

#2788 fix: Add missing free in dht_get_nodes_response event.
  toxcore/events/dht_get_nodes_response.c
Labels: bug

#2792 chore: Release 0.2.20
  CHANGELOG.md
  CMakeLists.txt
  configure.ac
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/docker/pkgsrc/pkgsrc.Dockerfile
  so.version
  toxcore/tox.h
Labels: chore

#2791 chore: Add check to ensure version numbers agree.
  .github/workflows/checks.yml
Labels: chore

#2774 feat(net): add missing connect to network struct
  auto_tests/TCP_test.c
  testing/fuzzing/fuzz_support.cc
  toxcore/TCP_client.c
  toxcore/network.c
  toxcore/network.h
  toxcore/network_test_util.cc
  toxcore/network_test_util.hh
Labels: enhancement, network, refactor

#2789 cleanup: Allocate logger using tox memory allocator.
  auto_tests/TCP_test.c
  auto_tests/announce_test.c
  auto_tests/forwarding_test.c
  auto_tests/onion_test.c
  other/DHT_bootstrap.c
  other/bootstrap_daemon/src/tox-bootstrapd.c
  toxcore/BUILD.bazel
  toxcore/DHT_fuzz_test.cc
  toxcore/DHT_test.cc
  toxcore/Messenger.c
  toxcore/forwarding_fuzz_test.cc
  toxcore/group_announce_fuzz_test.cc
  toxcore/group_announce_test.cc
  toxcore/group_moderation_test.cc
  toxcore/logger.c
  toxcore/logger.h
Labels: cleanup

#2796 chore: Migrate to conan 2.
  .circleci/config.yml
  CMakeLists.txt
  auto_tests/CMakeLists.txt
  auto_tests/encryptsave_test.c
  azure-pipelines.yml
  cmake/Dependencies.cmake
  conanfile.py
  testing/BUILD.bazel
  testing/CMakeLists.txt
  testing/Makefile.inc
  testing/misc_tools.c
Labels: chore

#2797 chore: Use vcpkg instead of conan in the MSVC build.
  CMakePresets.json
  azure-pipelines.yml
  conanfile.py
Labels: chore

#2694 feat: Add option to disable DNS lookups in toxcore.
  auto_tests/network_test.c
  other/DHT_bootstrap.c
  other/bootstrap_daemon/src/config.c
  testing/Messenger_test.c
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/Messenger.h
  toxcore/network.c
  toxcore/network.h
  toxcore/tox.c
  toxcore/tox.h
  toxcore/tox_api.c
  toxcore/tox_private.c
Labels: enhancement

#2773 feat(net): implement the address resolution network struct functions
  auto_tests/network_test.c
  toxcore/BUILD.bazel
  toxcore/DHT.c
  toxcore/network.c
  toxcore/network.h
  toxcore/network_test_util.cc
  toxcore/network_test_util.hh
  toxcore/tox.c
  toxcore/tox_private.c
Labels: enhancement, network, bootstrap, refactor
