Repository TokTok/c-toxcore, pull requests merged in 2024-03, with the labels that each got.

#2728 refactor: Observers/ignored peers can now send and receive custom packets
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/tox.c
  toxcore/tox.h
  toxcore/tox_api.c
Labels: refactor

#2727 feat: add message IDs to private group messages
  auto_tests/group_message_test.c
  other/event_tooling/generate_event_c.cpp
  toxcore/events/group_private_message.c
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/group_common.h
  toxcore/tox.c
  toxcore/tox.h
  toxcore/tox_events.h
Labels: enhancement

#2729 cleanup: use typedef for private message ID's in callback
  auto_tests/group_message_test.c
  toxcore/tox.c
  toxcore/tox.h
Labels: cleanup

#2731 cleanup: align group send err enum order
  toxcore/tox.h
  toxcore/tox_api.c
Labels: api break

#2736 cleanup: A more descriptive error for group invite accept function
  toxcore/tox.c
  toxcore/tox.h
  toxcore/tox_api.c
Labels: api break, cleanup

#2717 cleanup: Remove useless if clause
  toxcore/Messenger.c
Labels: cleanup
