Repository TokTok/c-toxcore, pull requests merged in 2025-01, with the labels that each got.

#2818 refactor: Use tox memory in group chats allocations.
  toxcore/group_chats.c
Labels: refactor

#2816 refactor: Use tox memory for group moderation/pack allocations.
  .cirrus.yml
  toxcore/group_moderation.c
  toxcore/group_onion_announce.c
  toxcore/group_pack.c
Labels: refactor

#2821 cleanup: Add a `TOX_HIDE_DEPRECATED` check to hide deprecated symbols.
  auto_tests/save_compatibility_test.c
  toxcore/tox.c
  toxcore/tox.h
Labels: cleanup

#2823 cleanup: Reduce stack frame sizes to below 4096 bytes.
  auto_tests/TCP_test.c
  auto_tests/save_compatibility_test.c
Labels: cleanup

#2808 docs: Update the docs for group join functions
  toxcore/group_chats.c
  toxcore/group_chats.h
  toxcore/tox.h
Labels: documentation, cleanup

#2824 feat: Add `to_string` functions for toxencryptsave errors.
  testing/BUILD.bazel
  testing/decrypt_save.c
  toxencryptsave/toxencryptsave.c
  toxencryptsave/toxencryptsave.h
Labels: enhancement

#2827 cleanup: Add missing `#include` to sort_test.cc.
  toxcore/sort_test.cc
Labels: cleanup

#2820 cleanup: Align internal logger with external on type of source line.
  .circleci/config.yml
  .cirrus.yml
  auto_tests/auto_test_support.c
  auto_tests/auto_test_support.h
  other/DHT_bootstrap.c
  other/bootstrap_daemon/src/tox-bootstrapd.c
  toxcore/logger.c
  toxcore/logger.h
  toxcore/tox.c
Labels: cleanup

#2817 refactor: Use tox memory in group connection allocations.
  .cirrus.yml
  toxcore/group_chats.c
  toxcore/group_connection.c
  toxcore/group_connection.h
Labels: refactor

#2828 fix: Allow TCP connections to fail `connect` calls.
  auto_tests/TCP_test.c
  toxcore/TCP_client.c
  toxcore/network.c
  toxcore/network.h
Labels: bug

#2765 fix: The logger drops frame with the "Success" status.
  toxav/rtp.c
Labels: bug

#2687 fix: Avoid `memcpy`-ing structs into onion ping id data.
  toxcore/onion_announce.c
  toxcore/onion_client.c
Labels: bug

#2830 cleanup: Check that onion IP/Port packing worked.
  toxcore/onion_announce.c
  toxcore/onion_client.c
Labels: cleanup

#2831 cleanup: Some random cleanups, mostly related to mem.
  auto_tests/proxy_test.c
  toxav/audio.c
  toxav/audio.h
  toxav/rtp.c
  toxav/rtp.h
  toxav/toxav.c
  toxav/video.c
  toxav/video.h
  toxcore/Messenger.c
  toxcore/group.c
  toxcore/group.h
  toxcore/group_chats.c
  toxcore/group_moderation.c
  toxcore/group_onion_announce.h
  toxcore/list.c
  toxcore/logger.c
  toxcore/mem.c
  toxcore/mem.h
  toxcore/mono_time.c
  toxcore/mono_time.h
  toxcore/net_crypto.c
  toxcore/net_crypto.h
  toxcore/tox.c
Labels: cleanup

#2760 fix: Fake broadcast address for 127.x.x.x
  toxcore/LAN_discovery.c
Labels: bug

#2833 cleanup: Use tox memory for bin_unpack and net_strerror.
  auto_tests/TCP_test.c
  auto_tests/network_test.c
  toxav/rtp.c
  toxav/rtp.h
  toxav/toxav.c
  toxcore/BUILD.bazel
  toxcore/Messenger.c
  toxcore/TCP_common.c
  toxcore/TCP_server.c
  toxcore/bin_pack_test.cc
  toxcore/bin_unpack.c
  toxcore/bin_unpack.h
  toxcore/network.c
  toxcore/network.h
  toxcore/tox_events.c
Labels: cleanup

#2834 fix: Don't crash on malloc failures in bin_unpack.
  toxcore/bin_unpack.c
Labels: bug

#2835 test: Add some more asserts for I/O and alloc to succeed.
  auto_tests/file_saving_test.c
Labels: test

#2819 refactor: Make Tox_Options own the passed proxy host and savedata.
  auto_tests/file_saving_test.c
  toxcore/tox.h
  toxcore/tox_api.c
Labels: refactor

#2836 cleanup: Avoid clashing with global define `DEBUG`.
  testing/fuzzing/bootstrap_fuzz_test.cc
  testing/fuzzing/e2e_fuzz_test.cc
  testing/fuzzing/fuzz_support.cc
  testing/fuzzing/fuzz_support.hh
  testing/fuzzing/protodump.cc
  testing/fuzzing/protodump_reduce.cc
Labels: cleanup

#2838 chore: Move most cirrus jobs to circleci.
  .circleci/config.yml
  .cirrus.yml
Labels: chore

#2841 refactor: Remove tox_types.h; use `struct` tags instead.
  BUILD.bazel
  CMakeLists.txt
  other/docker/pkgsrc/pkgsrc.patch
  toxcore/BUILD.bazel
  toxcore/Makefile.inc
  toxcore/tox.h
  toxcore/tox_options.h
  toxcore/tox_private.c
  toxcore/tox_private.h
  toxcore/tox_types.c
  toxcore/tox_types.h
Labels: refactor

#2842 cleanup: Mark events/dispatch headers as experimental.
  CMakeLists.txt
  other/docker/pkgsrc/pkgsrc.patch
Labels: cleanup

#2843 chore: Add binary deploy workflows.
  .github/scripts/cmake-android
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  other/deploy/android.sh
  other/deploy/deps.sh
  other/deploy/ios.sh
  other/deploy/linux.sh
  other/deploy/macos.sh
Labels: chore

#2847 chore: Support arm64 iphone simulator.
  .github/workflows/deploy.yml
  other/deploy/android.sh
  other/deploy/deps.sh
  other/deploy/ios.sh
  other/deploy/ios/LICENSE
  other/deploy/ios/make_framework
  other/deploy/ios/toxcore.podspec
  other/deploy/linux.sh
  other/deploy/macos.sh
Labels: chore

#2849 chore: Add ios/macos framework build.
  .github/workflows/deploy.yml
  other/deploy/apple/.gitignore
  other/deploy/apple/Info.plist
  other/deploy/apple/LICENSE
  other/deploy/apple/download-nightly.sh
  other/deploy/apple/make-framework.sh
  other/deploy/apple/toxcore.podspec
  other/deploy/ios/make_framework
Labels: chore

#2850 chore: Fix xcframework checksum creation.
  .github/workflows/deploy.yml
Labels: chore

#2853 refactor: don't fully discard received DHT nodes.
  toxcore/DHT.c
Labels: refactor

#2852 chore: Add opus and vpx to the toxcore wasm build.
  .github/workflows/docker.yml
  other/docker/wasm/run
  other/docker/wasm/wasm.Dockerfile
  other/docker/wasm/wasm.Dockerfile.dockerignore
  other/emscripten/Dockerfile
  other/emscripten/build
Labels: chore

#2856 fix: ip to string function not accepting tcp families
  toxcore/network.c
Labels: bug

#2738 cleanup: remove kicked peers from saved peers list
  toxcore/group_chats.c
Labels: cleanup

#2857 perf: Use stack allocation for strerror rendering.
  auto_tests/TCP_test.c
  auto_tests/network_test.c
  other/docker/cppcheck/toxcore.cfg
  toxav/rtp.c
  toxav/toxav.c
  toxcore/TCP_common.c
  toxcore/TCP_server.c
  toxcore/network.c
  toxcore/network.h
Labels: performance
