Repository TokTok/c-toxcore, pull requests merged in 2025-02, with the labels that each got.

#2860 cleanup: rename getnodes/sendnodes to nodes request/response
  CMakeLists.txt
  auto_tests/dht_getnodes_api_test.c
  toxcore/DHT.c
  toxcore/DHT.h
  toxcore/Makefile.inc
  toxcore/events/dht_get_nodes_response.c
  toxcore/events/dht_nodes_response.c
  toxcore/events/events_alloc.h
  toxcore/network.c
  toxcore/network.h
  toxcore/onion_client.c
  toxcore/tox.c
  toxcore/tox.h
  toxcore/tox_dispatch.c
  toxcore/tox_dispatch.h
  toxcore/tox_event.c
  toxcore/tox_event.h
  toxcore/tox_events.c
  toxcore/tox_events.h
  toxcore/tox_private.c
  toxcore/tox_private.h
  toxcore/tox_struct.h
Labels: api break, cleanup

#2861 refactor: Use IP string length from ip_ntoa instead of strlen.
  .cirrus.yml
  .github/workflows/ci.yml
  auto_tests/CMakeLists.txt
  auto_tests/dht_nodes_response_api_test.c
  toxav/toxav.c
  toxcore/events/dht_nodes_response.c
  toxcore/tox.c
  toxcore/tox_events.c
  toxcore/tox_private.c
  toxcore/tox_private.h
  toxcore/tox_struct.h
Labels: refactor

#2863 test: Add a Net_Crypto fuzz test.
  testing/fuzzing/CMakeLists.txt
  testing/fuzzing/bootstrap_fuzz_test.cc
  testing/fuzzing/e2e_fuzz_test.cc
  testing/fuzzing/fuzz_support.cc
  testing/fuzzing/fuzz_support.hh
  testing/fuzzing/protodump.cc
  testing/fuzzing/rebuild_protodump
  toxcore/BUILD.bazel
  toxcore/net_crypto.h
  toxcore/net_crypto_fuzz_test.cc
  toxcore/onion_client.c
Labels: test

#2865 chore: Add time option to manual fuzz trigger.
  .github/workflows/cflite_batch.yml
Labels: chore

#2868 chore: Add strict-abi support for macOS/iOS.
  cmake/StrictAbi.cmake
  other/deploy/android.sh
  other/deploy/ios.sh
  other/deploy/linux.sh
  other/deploy/macos.sh
Labels: chore

#2869 chore: Add wasm to the nightly binary deploys.
  .github/workflows/deploy.yml
  .github/workflows/docker.yml
Labels: chore

#2871 chore: Export wasmExports from the wasm binary.
  other/docker/wasm/wasm.Dockerfile
  toxcore/network.c
Labels: chore

#2872 docs: Update changelog format to use the new clog-compatible way.
  .cirrus.yml
  .clog.toml
  .github/workflows/ci.yml
  CHANGELOG.md
  other/deploy/ios.sh
  other/deploy/macos.sh
Labels: documentation

#2873 chore: Add deploy job for single C file library.
  .github/scripts/cmake-osx
  .github/workflows/deploy.yml
  other/docker/goblint/sodium.c
  other/make_single_file
Labels: chore

#2874 feat: Add a Makefile for the single file deploy build.
  .github/workflows/deploy.yml
  other/deploy/single-file/.gitignore
  other/deploy/single-file/Makefile
  other/deploy/single-file/make_single_file
  other/docker/goblint/goblint.Dockerfile
  other/docker/sparse/sparse.Dockerfile
  other/docker/tcc/tcc.Dockerfile
Labels: enhancement

#2875 chore: Move one of the 3 freebsd builds to post-submit.
  .github/workflows/ci.yml
  .github/workflows/post-submit.yml
Labels: chore

#2876 chore: Don't upload ios/macos variants in deploy workflows.
  .github/workflows/deploy.yml
Labels: chore

#2877 chore: Add a source tarball deploy workflow.
  .github/workflows/deploy.yml
Labels: chore

#2879 chore: Fix alpine-s390x build.
  other/docker/alpine-s390x/alpine-s390x.Dockerfile
  other/docker/alpine-s390x/alpine-s390x.Dockerfile.dockerignore
  other/docker/alpine-s390x/dockerignore
  other/docker/alpine-s390x/run
Labels: chore

#2878 chore: Add release issue template and workflow.
  .github/ISSUE_TEMPLATE/release.yml
  .github/workflows/draft.yml
  .github/workflows/release.yml
  .reviewable/completion.js
  .reviewable/settings.yaml
Labels: chore

#2880 chore: Use new bazel script for circle ci.
  .circleci/bazel-test
  .circleci/config.yml
  auto_tests/proxy_test.c
  other/proxy/proxy_server.go
Labels: chore

#2883 chore: Add version update script compatible with ci-tools.
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/version-sync
  tools/update-versions.sh
Labels: chore

#2885 chore: Update the version-sync script to work in a post-tox.api.h world
  other/version-sync
Labels: chore

#2886 chore: Update the pkgsrc versions in the update-versions tool
  other/version-sync
Labels: chore

#2882 chore: Release v0.2.21-rc.1
  CHANGELOG.md
  CMakeLists.txt
  configure.ac
  other/bootstrap_daemon/docker/tox-bootstrapd.sha256
  other/docker/pkgsrc/pkgsrc.Dockerfile
  other/docker/pkgsrc/pkgsrc.patch
  so.version
  third_party/.gitignore
  toxcore/tox.h
Labels: chore
